
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.1 EDK_P.7xd
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xspi.h"

/*
* The configuration table for devices
*/

XSpi_Config XSpi_ConfigTable[] =
{
	{
		XPAR_SPI_FLASH_DEVICE_ID,
		XPAR_SPI_FLASH_BASEADDR,
		XPAR_SPI_FLASH_FIFO_EXIST,
		XPAR_SPI_FLASH_SPI_SLAVE_ONLY,
		XPAR_SPI_FLASH_NUM_SS_BITS,
		XPAR_SPI_FLASH_NUM_TRANSFER_BITS,
		XPAR_SPI_FLASH_SPI_MODE
	}
};


