// ==============================================================
// File generated by AutoESL - High-Level Synthesis System (C, C++, SystemC)
// Version: 2012.1
// Copyright (C) 2012 Xilinx Inc. All rights reserved.
// 
// ==============================================================

// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/SC)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        others - reserved
// 0x10 : reserved
// 0x14 : Data signal of sum
//        bit 31~0 - sum[31:0] (Read)
// 0x18 : Data signal of sum
//        bit 31~0 - sum[63:32] (Read)
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XDISTANCE_SQUARED_CONTROL_BUS_ADDR_AP_CTRL  0x00
#define XDISTANCE_SQUARED_CONTROL_BUS_ADDR_GIE      0x04
#define XDISTANCE_SQUARED_CONTROL_BUS_ADDR_IER      0x08
#define XDISTANCE_SQUARED_CONTROL_BUS_ADDR_ISR      0x0c
#define XDISTANCE_SQUARED_CONTROL_BUS_ADDR_SUM_DATA 0x14
#define XDISTANCE_SQUARED_CONTROL_BUS_BITS_SUM_DATA 64
