// ==============================================================
// File generated by AutoESL - High-Level Synthesis System (C, C++, SystemC)
// Version: 2012.1
// Copyright (C) 2012 Xilinx Inc. All rights reserved.
// 
// ==============================================================


`timescale 1ns/1ps

module distance_squared_grp_fu_238_ACMP_sitodp_5
#(parameter
    ID         = 5,
    NUM_STAGE  = 4,
    din0_WIDTH = 64,
    dout_WIDTH = 64
)(
    input  wire                  clk,
    input  wire                  reset,
    input  wire                  ce,
    input  wire [din0_WIDTH-1:0] din0,
    output wire [dout_WIDTH-1:0] dout
);
//------------------------Local signal-------------------
wire                  aclk;
wire                  aclken;
wire                  a_tvalid;
wire [63:0]           a_tdata;
wire                  r_tvalid;
wire [63:0]           r_tdata;
reg                   ce_buf1;
reg  [din0_WIDTH-1:0] din0_buf1;
//------------------------Instantiation------------------
distance_squared_ap_sitodp_2_no_dsp distance_squared_ap_sitodp_2_no_dsp_u (
    .aclk                 ( aclk ),
    .aclken               ( aclken ),
    .s_axis_a_tvalid      ( a_tvalid ),
    .s_axis_a_tdata       ( a_tdata ),
    .m_axis_result_tvalid ( r_tvalid ),
    .m_axis_result_tdata  ( r_tdata )
);
//------------------------Body---------------------------
assign aclk     = clk;
assign aclken   = ce_buf1;
assign a_tvalid = 1'b1;
assign a_tdata  = din0_buf1;
assign dout     = r_tdata;

always @(posedge clk) begin
    ce_buf1   <= ce;
    din0_buf1 <= din0;
end

endmodule
