// ==============================================================
// RTL generated by AutoESL - High-Level Synthesis System (C, C++, SystemC)
// Version: 2012.1
// Copyright (C) 2012 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "distance_squared.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic distance_squared::ap_const_logic_1 = SC_LOGIC_1;
const sc_logic distance_squared::ap_const_logic_0 = SC_LOGIC_0;
const sc_lv<6> distance_squared::ap_ST_st0_fsm_0 = "000000";
const sc_lv<6> distance_squared::ap_ST_st1_fsm_1 = "000001";
const sc_lv<6> distance_squared::ap_ST_st2_fsm_2 = "000010";
const sc_lv<6> distance_squared::ap_ST_st3_fsm_3 = "000011";
const sc_lv<6> distance_squared::ap_ST_st4_fsm_4 = "000100";
const sc_lv<6> distance_squared::ap_ST_pp0_stg0_fsm_5 = "000101";
const sc_lv<6> distance_squared::ap_ST_st28_fsm_6 = "000110";
const sc_lv<6> distance_squared::ap_ST_st29_fsm_7 = "000111";
const sc_lv<6> distance_squared::ap_ST_st30_fsm_8 = "001000";
const sc_lv<6> distance_squared::ap_ST_st31_fsm_9 = "001001";
const sc_lv<6> distance_squared::ap_ST_st32_fsm_10 = "001010";
const sc_lv<6> distance_squared::ap_ST_st33_fsm_11 = "001011";
const sc_lv<6> distance_squared::ap_ST_st34_fsm_12 = "001100";
const sc_lv<6> distance_squared::ap_ST_st35_fsm_13 = "001101";
const sc_lv<6> distance_squared::ap_ST_st36_fsm_14 = "001110";
const sc_lv<6> distance_squared::ap_ST_st37_fsm_15 = "001111";
const sc_lv<6> distance_squared::ap_ST_st38_fsm_16 = "010000";
const sc_lv<6> distance_squared::ap_ST_st39_fsm_17 = "010001";
const sc_lv<6> distance_squared::ap_ST_st40_fsm_18 = "010010";
const sc_lv<6> distance_squared::ap_ST_st41_fsm_19 = "010011";
const sc_lv<6> distance_squared::ap_ST_st42_fsm_20 = "010100";
const sc_lv<6> distance_squared::ap_ST_st43_fsm_21 = "010101";
const sc_lv<6> distance_squared::ap_ST_st44_fsm_22 = "010110";
const sc_lv<6> distance_squared::ap_ST_st45_fsm_23 = "010111";
const sc_lv<6> distance_squared::ap_ST_st46_fsm_24 = "011000";
const sc_lv<6> distance_squared::ap_ST_st47_fsm_25 = "011001";
const sc_lv<6> distance_squared::ap_ST_st48_fsm_26 = "011010";
const sc_lv<6> distance_squared::ap_ST_st49_fsm_27 = "011011";
const sc_lv<6> distance_squared::ap_ST_st50_fsm_28 = "011100";
const sc_lv<6> distance_squared::ap_ST_st51_fsm_29 = "011101";
const sc_lv<6> distance_squared::ap_ST_st52_fsm_30 = "011110";
const sc_lv<6> distance_squared::ap_ST_st53_fsm_31 = "011111";
const sc_lv<6> distance_squared::ap_ST_st54_fsm_32 = "100000";
const sc_lv<6> distance_squared::ap_ST_st55_fsm_33 = "100001";
const sc_lv<6> distance_squared::ap_ST_st56_fsm_34 = "100010";
const sc_lv<6> distance_squared::ap_ST_st57_fsm_35 = "100011";
const sc_lv<6> distance_squared::ap_ST_st58_fsm_36 = "100100";
const sc_lv<6> distance_squared::ap_ST_st59_fsm_37 = "100101";
const sc_lv<6> distance_squared::ap_ST_st60_fsm_38 = "100110";
const sc_lv<6> distance_squared::ap_ST_st61_fsm_39 = "100111";
const sc_lv<6> distance_squared::ap_ST_st62_fsm_40 = "101000";
const sc_lv<6> distance_squared::ap_ST_st63_fsm_41 = "101001";
const sc_lv<6> distance_squared::ap_ST_st64_fsm_42 = "101010";
const sc_lv<6> distance_squared::ap_ST_st65_fsm_43 = "101011";
const sc_lv<6> distance_squared::ap_ST_st66_fsm_44 = "101100";
const sc_lv<1> distance_squared::ap_const_lv1_0 = "0";
const sc_lv<8> distance_squared::ap_const_lv8_0 = "00000000";
const sc_lv<64> distance_squared::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<64> distance_squared::ap_const_lv64_1 = "0000000000000000000000000000000000000000000000000000000000000001";
const sc_lv<64> distance_squared::ap_const_lv64_2 = "0000000000000000000000000000000000000000000000000000000000000010";
const sc_lv<64> distance_squared::ap_const_lv64_3 = "0000000000000000000000000000000000000000000000000000000000000011";
const sc_lv<64> distance_squared::ap_const_lv64_4 = "0000000000000000000000000000000000000000000000000000000000000100";
const sc_lv<64> distance_squared::ap_const_lv64_5 = "0000000000000000000000000000000000000000000000000000000000000101";
const sc_lv<64> distance_squared::ap_const_lv64_6 = "0000000000000000000000000000000000000000000000000000000000000110";
const sc_lv<64> distance_squared::ap_const_lv64_7 = "0000000000000000000000000000000000000000000000000000000000000111";
const sc_lv<64> distance_squared::ap_const_lv64_8000000000000000 = "1000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<8> distance_squared::ap_const_lv8_C8 = "11001000";
const sc_lv<8> distance_squared::ap_const_lv8_1 = "00000001";
const sc_lv<2> distance_squared::ap_const_lv2_0 = "00";
const sc_lv<2> distance_squared::ap_const_lv2_1 = "01";
const sc_lv<5> distance_squared::ap_const_lv5_1 = "00001";

distance_squared::distance_squared(sc_module_name name) : sc_module(name), mVcdFile(0) {
    sum_of_squares_split_U = new distance_squared_sum_of_squares_split("sum_of_squares_split_U");
    sum_of_squares_split_U->clk(ap_clk);
    sum_of_squares_split_U->reset(ap_rst);
    sum_of_squares_split_U->address0(sum_of_squares_split_address0);
    sum_of_squares_split_U->ce0(sum_of_squares_split_ce0);
    sum_of_squares_split_U->we0(sum_of_squares_split_we0);
    sum_of_squares_split_U->d0(sum_of_squares_split_d0);
    sum_of_squares_split_U->q0(sum_of_squares_split_q0);
    sum_of_squares_split_U->address1(sum_of_squares_split_address1);
    sum_of_squares_split_U->ce1(sum_of_squares_split_ce1);
    sum_of_squares_split_U->we1(sum_of_squares_split_we1);
    sum_of_squares_split_U->d1(sum_of_squares_split_d1);
    distance_squared_grp_fu_219_ACMP_dadddsub_1_U = new distance_squared_grp_fu_219_ACMP_dadddsub_1<1,5,64,64,64>("distance_squared_grp_fu_219_ACMP_dadddsub_1_U");
    distance_squared_grp_fu_219_ACMP_dadddsub_1_U->clk(ap_clk);
    distance_squared_grp_fu_219_ACMP_dadddsub_1_U->reset(ap_rst);
    distance_squared_grp_fu_219_ACMP_dadddsub_1_U->din0(grp_fu_219_p0);
    distance_squared_grp_fu_219_ACMP_dadddsub_1_U->din1(grp_fu_219_p1);
    distance_squared_grp_fu_219_ACMP_dadddsub_1_U->opcode(grp_fu_219_opcode);
    distance_squared_grp_fu_219_ACMP_dadddsub_1_U->ce(grp_fu_219_ce);
    distance_squared_grp_fu_219_ACMP_dadddsub_1_U->dout(grp_fu_219_p2);
    distance_squared_grp_fu_223_ACMP_dadd_2_U = new distance_squared_grp_fu_223_ACMP_dadd_2<2,5,64,64,64>("distance_squared_grp_fu_223_ACMP_dadd_2_U");
    distance_squared_grp_fu_223_ACMP_dadd_2_U->clk(ap_clk);
    distance_squared_grp_fu_223_ACMP_dadd_2_U->reset(ap_rst);
    distance_squared_grp_fu_223_ACMP_dadd_2_U->din0(grp_fu_223_p0);
    distance_squared_grp_fu_223_ACMP_dadd_2_U->din1(grp_fu_223_p1);
    distance_squared_grp_fu_223_ACMP_dadd_2_U->ce(grp_fu_223_ce);
    distance_squared_grp_fu_223_ACMP_dadd_2_U->dout(grp_fu_223_p2);
    distance_squared_grp_fu_228_ACMP_dmul_3_U = new distance_squared_grp_fu_228_ACMP_dmul_3<3,6,64,64,64>("distance_squared_grp_fu_228_ACMP_dmul_3_U");
    distance_squared_grp_fu_228_ACMP_dmul_3_U->clk(ap_clk);
    distance_squared_grp_fu_228_ACMP_dmul_3_U->reset(ap_rst);
    distance_squared_grp_fu_228_ACMP_dmul_3_U->din0(grp_fu_228_p0);
    distance_squared_grp_fu_228_ACMP_dmul_3_U->din1(grp_fu_228_p1);
    distance_squared_grp_fu_228_ACMP_dmul_3_U->ce(grp_fu_228_ce);
    distance_squared_grp_fu_228_ACMP_dmul_3_U->dout(grp_fu_228_p2);
    distance_squared_grp_fu_232_ACMP_dcmp_4_U = new distance_squared_grp_fu_232_ACMP_dcmp_4<4,3,64,64,1>("distance_squared_grp_fu_232_ACMP_dcmp_4_U");
    distance_squared_grp_fu_232_ACMP_dcmp_4_U->clk(ap_clk);
    distance_squared_grp_fu_232_ACMP_dcmp_4_U->reset(ap_rst);
    distance_squared_grp_fu_232_ACMP_dcmp_4_U->din0(grp_fu_232_p0);
    distance_squared_grp_fu_232_ACMP_dcmp_4_U->din1(grp_fu_232_p1);
    distance_squared_grp_fu_232_ACMP_dcmp_4_U->ce(grp_fu_232_ce);
    distance_squared_grp_fu_232_ACMP_dcmp_4_U->opcode(grp_fu_232_opcode);
    distance_squared_grp_fu_232_ACMP_dcmp_4_U->dout(grp_fu_232_p2);
    distance_squared_grp_fu_238_ACMP_sitodp_5_U = new distance_squared_grp_fu_238_ACMP_sitodp_5<5,4,64,64>("distance_squared_grp_fu_238_ACMP_sitodp_5_U");
    distance_squared_grp_fu_238_ACMP_sitodp_5_U->clk(ap_clk);
    distance_squared_grp_fu_238_ACMP_sitodp_5_U->reset(ap_rst);
    distance_squared_grp_fu_238_ACMP_sitodp_5_U->din0(grp_fu_238_p0);
    distance_squared_grp_fu_238_ACMP_sitodp_5_U->ce(grp_fu_238_ce);
    distance_squared_grp_fu_238_ACMP_sitodp_5_U->dout(grp_fu_238_p1);
    distance_squared_grp_fu_241_ACMP_sitodp_6_U = new distance_squared_grp_fu_241_ACMP_sitodp_6<6,4,64,64>("distance_squared_grp_fu_241_ACMP_sitodp_6_U");
    distance_squared_grp_fu_241_ACMP_sitodp_6_U->clk(ap_clk);
    distance_squared_grp_fu_241_ACMP_sitodp_6_U->reset(ap_rst);
    distance_squared_grp_fu_241_ACMP_sitodp_6_U->din0(grp_fu_241_p0);
    distance_squared_grp_fu_241_ACMP_sitodp_6_U->ce(grp_fu_241_ce);
    distance_squared_grp_fu_241_ACMP_sitodp_6_U->dout(grp_fu_241_p1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it21 );
    sensitive << ( ap_reg_ppiten_pp0_it22 );
    sensitive << ( exitcond1_fu_258_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_100);
    sensitive << ( vector1_data_V_empty_n );
    sensitive << ( vector2_data_V_empty_n );
    sensitive << ( exitcond1_reg_326 );

    SC_METHOD(thread_exitcond1_fu_258_p2);
    sensitive << ( dim_reg_207 );

    SC_METHOD(thread_grp_fu_219_ce);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_326_pp0_it9 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_326_pp0_it5 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_326_pp0_it6 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_326_pp0_it7 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_326_pp0_it8 );

    SC_METHOD(thread_grp_fu_219_opcode);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it6 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_326_pp0_it5 );

    SC_METHOD(thread_grp_fu_219_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it6 );
    sensitive << ( reg_251 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_326_pp0_it5 );
    sensitive << ( vector1_data_reg_350 );

    SC_METHOD(thread_grp_fu_219_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( reg_244 );
    sensitive << ( ap_reg_ppiten_pp0_it6 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_326_pp0_it5 );
    sensitive << ( vector2_data_reg_355 );
    sensitive << ( sum_of_squares_reg_376 );

    SC_METHOD(thread_grp_fu_223_ce);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_326_pp0_it16 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_326_pp0_it17 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_326_pp0_it18 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_326_pp0_it19 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_326_pp0_it20 );

    SC_METHOD(thread_grp_fu_223_p0);
    sensitive << ( reg_251 );

    SC_METHOD(thread_grp_fu_223_p1);
    sensitive << ( diff_squared_reg_366 );

    SC_METHOD(thread_grp_fu_228_ce);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_326_pp0_it15 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_326_pp0_it10 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_326_pp0_it11 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_326_pp0_it12 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_326_pp0_it13 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_326_pp0_it14 );

    SC_METHOD(thread_grp_fu_228_p0);
    sensitive << ( reg_244 );

    SC_METHOD(thread_grp_fu_228_p1);
    sensitive << ( reg_244 );

    SC_METHOD(thread_grp_fu_232_ce);

    SC_METHOD(thread_grp_fu_232_opcode);

    SC_METHOD(thread_grp_fu_232_p0);
    sensitive << ( sum_of_squares_split_q0 );

    SC_METHOD(thread_grp_fu_232_p1);

    SC_METHOD(thread_grp_fu_238_ce);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_326_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_326_pp0_it2 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_326_pp0_it3 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_326_pp0_it4 );

    SC_METHOD(thread_grp_fu_238_p0);
    sensitive << ( vector1_data_V_read_reg_340 );

    SC_METHOD(thread_grp_fu_241_ce);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_326_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_326_pp0_it2 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_326_pp0_it3 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_326_pp0_it4 );

    SC_METHOD(thread_grp_fu_241_p0);
    sensitive << ( vector2_data_V_read_reg_345 );

    SC_METHOD(thread_sum);
    sensitive << ( grp_fu_219_p2 );

    SC_METHOD(thread_sum_of_squares_split_addr_1_gep_fu_139_p3);

    SC_METHOD(thread_sum_of_squares_split_addr_2_gep_fu_152_p3);

    SC_METHOD(thread_sum_of_squares_split_addr_3_gep_fu_160_p3);

    SC_METHOD(thread_sum_of_squares_split_addr_4_gep_fu_168_p3);

    SC_METHOD(thread_sum_of_squares_split_addr_5_gep_fu_176_p3);

    SC_METHOD(thread_sum_of_squares_split_addr_6_gep_fu_184_p3);

    SC_METHOD(thread_sum_of_squares_split_addr_7_gep_fu_192_p3);

    SC_METHOD(thread_sum_of_squares_split_addr_8_reg_3600);
    sensitive << ( ap_reg_ppstg_dim_cast2_reg_335_pp0_it14 );

    SC_METHOD(thread_sum_of_squares_split_addr_gep_fu_125_p3);

    SC_METHOD(thread_sum_of_squares_split_address0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it15 );
    sensitive << ( sum_of_squares_split_addr_reg_286 );
    sensitive << ( sum_of_squares_split_addr_1_reg_291 );
    sensitive << ( sum_of_squares_split_addr_2_reg_296 );
    sensitive << ( sum_of_squares_split_addr_3_reg_301 );
    sensitive << ( sum_of_squares_split_addr_4_reg_306 );
    sensitive << ( sum_of_squares_split_addr_5_reg_311 );
    sensitive << ( sum_of_squares_split_addr_6_reg_316 );
    sensitive << ( sum_of_squares_split_addr_7_reg_321 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_326_pp0_it14 );
    sensitive << ( tmp_2_fu_274_p1 );

    SC_METHOD(thread_sum_of_squares_split_address1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it22 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_326_pp0_it21 );
    sensitive << ( ap_reg_ppstg_sum_of_squares_split_addr_8_reg_360_pp0_it21 );

    SC_METHOD(thread_sum_of_squares_split_ce0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it15 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_326_pp0_it14 );

    SC_METHOD(thread_sum_of_squares_split_ce1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it22 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_326_pp0_it21 );

    SC_METHOD(thread_sum_of_squares_split_d0);

    SC_METHOD(thread_sum_of_squares_split_d1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it22 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_326_pp0_it21 );
    sensitive << ( tmp_3_reg_371 );

    SC_METHOD(thread_sum_of_squares_split_we0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_sum_of_squares_split_we1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it22 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_326_pp0_it21 );

    SC_METHOD(thread_tmp_2_fu_274_p1);
    sensitive << ( ap_reg_ppstg_dim_cast2_reg_335_pp0_it14 );

    SC_METHOD(thread_vector1_data_V_read);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond1_reg_326 );
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_vector1_keep_V_read);

    SC_METHOD(thread_vector1_last_V_read);

    SC_METHOD(thread_vector2_data_V_read);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond1_reg_326 );
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_vector2_keep_V_read);

    SC_METHOD(thread_vector2_last_V_read);

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "000000";
    ap_reg_ppiten_pp0_it10 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it2 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it3 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it4 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it5 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it6 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it7 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it8 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it9 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it11 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it12 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it13 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it14 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it15 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it16 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it17 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it18 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it19 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it20 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it21 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it22 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "distance_squared_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(-12);
    const char* dump_vcd = std::getenv("AP_WRITE_VCD");
    if (dump_vcd) {
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, vector1_data_V_dout, "(port)vector1_data_V_dout");
    sc_trace(mVcdFile, vector1_data_V_empty_n, "(port)vector1_data_V_empty_n");
    sc_trace(mVcdFile, vector1_data_V_read, "(port)vector1_data_V_read");
    sc_trace(mVcdFile, vector1_keep_V_dout, "(port)vector1_keep_V_dout");
    sc_trace(mVcdFile, vector1_keep_V_empty_n, "(port)vector1_keep_V_empty_n");
    sc_trace(mVcdFile, vector1_keep_V_read, "(port)vector1_keep_V_read");
    sc_trace(mVcdFile, vector1_last_V_dout, "(port)vector1_last_V_dout");
    sc_trace(mVcdFile, vector1_last_V_empty_n, "(port)vector1_last_V_empty_n");
    sc_trace(mVcdFile, vector1_last_V_read, "(port)vector1_last_V_read");
    sc_trace(mVcdFile, vector2_data_V_dout, "(port)vector2_data_V_dout");
    sc_trace(mVcdFile, vector2_data_V_empty_n, "(port)vector2_data_V_empty_n");
    sc_trace(mVcdFile, vector2_data_V_read, "(port)vector2_data_V_read");
    sc_trace(mVcdFile, vector2_keep_V_dout, "(port)vector2_keep_V_dout");
    sc_trace(mVcdFile, vector2_keep_V_empty_n, "(port)vector2_keep_V_empty_n");
    sc_trace(mVcdFile, vector2_keep_V_read, "(port)vector2_keep_V_read");
    sc_trace(mVcdFile, vector2_last_V_dout, "(port)vector2_last_V_dout");
    sc_trace(mVcdFile, vector2_last_V_empty_n, "(port)vector2_last_V_empty_n");
    sc_trace(mVcdFile, vector2_last_V_read, "(port)vector2_last_V_read");
    sc_trace(mVcdFile, sum, "(port)sum");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, dim_reg_207, "dim_reg_207");
    sc_trace(mVcdFile, grp_fu_219_p2, "grp_fu_219_p2");
    sc_trace(mVcdFile, reg_244, "reg_244");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it10, "ap_reg_ppiten_pp0_it10");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, exitcond1_reg_326, "exitcond1_reg_326");
    sc_trace(mVcdFile, ap_sig_bdd_100, "ap_sig_bdd_100");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it2, "ap_reg_ppiten_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it3, "ap_reg_ppiten_pp0_it3");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it4, "ap_reg_ppiten_pp0_it4");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it5, "ap_reg_ppiten_pp0_it5");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it6, "ap_reg_ppiten_pp0_it6");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it7, "ap_reg_ppiten_pp0_it7");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it8, "ap_reg_ppiten_pp0_it8");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it9, "ap_reg_ppiten_pp0_it9");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it11, "ap_reg_ppiten_pp0_it11");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it12, "ap_reg_ppiten_pp0_it12");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it13, "ap_reg_ppiten_pp0_it13");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it14, "ap_reg_ppiten_pp0_it14");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it15, "ap_reg_ppiten_pp0_it15");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it16, "ap_reg_ppiten_pp0_it16");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it17, "ap_reg_ppiten_pp0_it17");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it18, "ap_reg_ppiten_pp0_it18");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it19, "ap_reg_ppiten_pp0_it19");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it20, "ap_reg_ppiten_pp0_it20");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it21, "ap_reg_ppiten_pp0_it21");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it22, "ap_reg_ppiten_pp0_it22");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond1_reg_326_pp0_it9, "ap_reg_ppstg_exitcond1_reg_326_pp0_it9");
    sc_trace(mVcdFile, sum_of_squares_split_q0, "sum_of_squares_split_q0");
    sc_trace(mVcdFile, reg_251, "reg_251");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond1_reg_326_pp0_it15, "ap_reg_ppstg_exitcond1_reg_326_pp0_it15");
    sc_trace(mVcdFile, sum_of_squares_split_addr_gep_fu_125_p3, "sum_of_squares_split_addr_gep_fu_125_p3");
    sc_trace(mVcdFile, sum_of_squares_split_addr_reg_286, "sum_of_squares_split_addr_reg_286");
    sc_trace(mVcdFile, sum_of_squares_split_addr_1_gep_fu_139_p3, "sum_of_squares_split_addr_1_gep_fu_139_p3");
    sc_trace(mVcdFile, sum_of_squares_split_addr_1_reg_291, "sum_of_squares_split_addr_1_reg_291");
    sc_trace(mVcdFile, sum_of_squares_split_addr_2_gep_fu_152_p3, "sum_of_squares_split_addr_2_gep_fu_152_p3");
    sc_trace(mVcdFile, sum_of_squares_split_addr_2_reg_296, "sum_of_squares_split_addr_2_reg_296");
    sc_trace(mVcdFile, sum_of_squares_split_addr_3_gep_fu_160_p3, "sum_of_squares_split_addr_3_gep_fu_160_p3");
    sc_trace(mVcdFile, sum_of_squares_split_addr_3_reg_301, "sum_of_squares_split_addr_3_reg_301");
    sc_trace(mVcdFile, sum_of_squares_split_addr_4_gep_fu_168_p3, "sum_of_squares_split_addr_4_gep_fu_168_p3");
    sc_trace(mVcdFile, sum_of_squares_split_addr_4_reg_306, "sum_of_squares_split_addr_4_reg_306");
    sc_trace(mVcdFile, sum_of_squares_split_addr_5_gep_fu_176_p3, "sum_of_squares_split_addr_5_gep_fu_176_p3");
    sc_trace(mVcdFile, sum_of_squares_split_addr_5_reg_311, "sum_of_squares_split_addr_5_reg_311");
    sc_trace(mVcdFile, sum_of_squares_split_addr_6_gep_fu_184_p3, "sum_of_squares_split_addr_6_gep_fu_184_p3");
    sc_trace(mVcdFile, sum_of_squares_split_addr_6_reg_316, "sum_of_squares_split_addr_6_reg_316");
    sc_trace(mVcdFile, sum_of_squares_split_addr_7_gep_fu_192_p3, "sum_of_squares_split_addr_7_gep_fu_192_p3");
    sc_trace(mVcdFile, sum_of_squares_split_addr_7_reg_321, "sum_of_squares_split_addr_7_reg_321");
    sc_trace(mVcdFile, exitcond1_fu_258_p2, "exitcond1_fu_258_p2");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond1_reg_326_pp0_it1, "ap_reg_ppstg_exitcond1_reg_326_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond1_reg_326_pp0_it2, "ap_reg_ppstg_exitcond1_reg_326_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond1_reg_326_pp0_it3, "ap_reg_ppstg_exitcond1_reg_326_pp0_it3");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond1_reg_326_pp0_it4, "ap_reg_ppstg_exitcond1_reg_326_pp0_it4");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond1_reg_326_pp0_it5, "ap_reg_ppstg_exitcond1_reg_326_pp0_it5");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond1_reg_326_pp0_it6, "ap_reg_ppstg_exitcond1_reg_326_pp0_it6");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond1_reg_326_pp0_it7, "ap_reg_ppstg_exitcond1_reg_326_pp0_it7");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond1_reg_326_pp0_it8, "ap_reg_ppstg_exitcond1_reg_326_pp0_it8");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond1_reg_326_pp0_it10, "ap_reg_ppstg_exitcond1_reg_326_pp0_it10");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond1_reg_326_pp0_it11, "ap_reg_ppstg_exitcond1_reg_326_pp0_it11");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond1_reg_326_pp0_it12, "ap_reg_ppstg_exitcond1_reg_326_pp0_it12");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond1_reg_326_pp0_it13, "ap_reg_ppstg_exitcond1_reg_326_pp0_it13");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond1_reg_326_pp0_it14, "ap_reg_ppstg_exitcond1_reg_326_pp0_it14");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond1_reg_326_pp0_it16, "ap_reg_ppstg_exitcond1_reg_326_pp0_it16");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond1_reg_326_pp0_it17, "ap_reg_ppstg_exitcond1_reg_326_pp0_it17");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond1_reg_326_pp0_it18, "ap_reg_ppstg_exitcond1_reg_326_pp0_it18");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond1_reg_326_pp0_it19, "ap_reg_ppstg_exitcond1_reg_326_pp0_it19");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond1_reg_326_pp0_it20, "ap_reg_ppstg_exitcond1_reg_326_pp0_it20");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond1_reg_326_pp0_it21, "ap_reg_ppstg_exitcond1_reg_326_pp0_it21");
    sc_trace(mVcdFile, dim_cast2_reg_335, "dim_cast2_reg_335");
    sc_trace(mVcdFile, ap_reg_ppstg_dim_cast2_reg_335_pp0_it1, "ap_reg_ppstg_dim_cast2_reg_335_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppstg_dim_cast2_reg_335_pp0_it2, "ap_reg_ppstg_dim_cast2_reg_335_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppstg_dim_cast2_reg_335_pp0_it3, "ap_reg_ppstg_dim_cast2_reg_335_pp0_it3");
    sc_trace(mVcdFile, ap_reg_ppstg_dim_cast2_reg_335_pp0_it4, "ap_reg_ppstg_dim_cast2_reg_335_pp0_it4");
    sc_trace(mVcdFile, ap_reg_ppstg_dim_cast2_reg_335_pp0_it5, "ap_reg_ppstg_dim_cast2_reg_335_pp0_it5");
    sc_trace(mVcdFile, ap_reg_ppstg_dim_cast2_reg_335_pp0_it6, "ap_reg_ppstg_dim_cast2_reg_335_pp0_it6");
    sc_trace(mVcdFile, ap_reg_ppstg_dim_cast2_reg_335_pp0_it7, "ap_reg_ppstg_dim_cast2_reg_335_pp0_it7");
    sc_trace(mVcdFile, ap_reg_ppstg_dim_cast2_reg_335_pp0_it8, "ap_reg_ppstg_dim_cast2_reg_335_pp0_it8");
    sc_trace(mVcdFile, ap_reg_ppstg_dim_cast2_reg_335_pp0_it9, "ap_reg_ppstg_dim_cast2_reg_335_pp0_it9");
    sc_trace(mVcdFile, ap_reg_ppstg_dim_cast2_reg_335_pp0_it10, "ap_reg_ppstg_dim_cast2_reg_335_pp0_it10");
    sc_trace(mVcdFile, ap_reg_ppstg_dim_cast2_reg_335_pp0_it11, "ap_reg_ppstg_dim_cast2_reg_335_pp0_it11");
    sc_trace(mVcdFile, ap_reg_ppstg_dim_cast2_reg_335_pp0_it12, "ap_reg_ppstg_dim_cast2_reg_335_pp0_it12");
    sc_trace(mVcdFile, ap_reg_ppstg_dim_cast2_reg_335_pp0_it13, "ap_reg_ppstg_dim_cast2_reg_335_pp0_it13");
    sc_trace(mVcdFile, ap_reg_ppstg_dim_cast2_reg_335_pp0_it14, "ap_reg_ppstg_dim_cast2_reg_335_pp0_it14");
    sc_trace(mVcdFile, vector1_data_V_read_reg_340, "vector1_data_V_read_reg_340");
    sc_trace(mVcdFile, vector2_data_V_read_reg_345, "vector2_data_V_read_reg_345");
    sc_trace(mVcdFile, grp_fu_238_p1, "grp_fu_238_p1");
    sc_trace(mVcdFile, vector1_data_reg_350, "vector1_data_reg_350");
    sc_trace(mVcdFile, grp_fu_241_p1, "grp_fu_241_p1");
    sc_trace(mVcdFile, vector2_data_reg_355, "vector2_data_reg_355");
    sc_trace(mVcdFile, sum_of_squares_split_addr_8_reg_360, "sum_of_squares_split_addr_8_reg_360");
    sc_trace(mVcdFile, ap_reg_ppstg_sum_of_squares_split_addr_8_reg_360_pp0_it16, "ap_reg_ppstg_sum_of_squares_split_addr_8_reg_360_pp0_it16");
    sc_trace(mVcdFile, ap_reg_ppstg_sum_of_squares_split_addr_8_reg_360_pp0_it17, "ap_reg_ppstg_sum_of_squares_split_addr_8_reg_360_pp0_it17");
    sc_trace(mVcdFile, ap_reg_ppstg_sum_of_squares_split_addr_8_reg_360_pp0_it18, "ap_reg_ppstg_sum_of_squares_split_addr_8_reg_360_pp0_it18");
    sc_trace(mVcdFile, ap_reg_ppstg_sum_of_squares_split_addr_8_reg_360_pp0_it19, "ap_reg_ppstg_sum_of_squares_split_addr_8_reg_360_pp0_it19");
    sc_trace(mVcdFile, ap_reg_ppstg_sum_of_squares_split_addr_8_reg_360_pp0_it20, "ap_reg_ppstg_sum_of_squares_split_addr_8_reg_360_pp0_it20");
    sc_trace(mVcdFile, ap_reg_ppstg_sum_of_squares_split_addr_8_reg_360_pp0_it21, "ap_reg_ppstg_sum_of_squares_split_addr_8_reg_360_pp0_it21");
    sc_trace(mVcdFile, grp_fu_228_p2, "grp_fu_228_p2");
    sc_trace(mVcdFile, diff_squared_reg_366, "diff_squared_reg_366");
    sc_trace(mVcdFile, grp_fu_223_p2, "grp_fu_223_p2");
    sc_trace(mVcdFile, tmp_3_reg_371, "tmp_3_reg_371");
    sc_trace(mVcdFile, sum_of_squares_reg_376, "sum_of_squares_reg_376");
    sc_trace(mVcdFile, sum_of_squares_split_address0, "sum_of_squares_split_address0");
    sc_trace(mVcdFile, sum_of_squares_split_ce0, "sum_of_squares_split_ce0");
    sc_trace(mVcdFile, sum_of_squares_split_we0, "sum_of_squares_split_we0");
    sc_trace(mVcdFile, sum_of_squares_split_d0, "sum_of_squares_split_d0");
    sc_trace(mVcdFile, sum_of_squares_split_address1, "sum_of_squares_split_address1");
    sc_trace(mVcdFile, sum_of_squares_split_ce1, "sum_of_squares_split_ce1");
    sc_trace(mVcdFile, sum_of_squares_split_we1, "sum_of_squares_split_we1");
    sc_trace(mVcdFile, sum_of_squares_split_d1, "sum_of_squares_split_d1");
    sc_trace(mVcdFile, tmp_2_fu_274_p1, "tmp_2_fu_274_p1");
    sc_trace(mVcdFile, grp_fu_219_p0, "grp_fu_219_p0");
    sc_trace(mVcdFile, grp_fu_219_p1, "grp_fu_219_p1");
    sc_trace(mVcdFile, grp_fu_223_p0, "grp_fu_223_p0");
    sc_trace(mVcdFile, grp_fu_223_p1, "grp_fu_223_p1");
    sc_trace(mVcdFile, grp_fu_228_p0, "grp_fu_228_p0");
    sc_trace(mVcdFile, grp_fu_228_p1, "grp_fu_228_p1");
    sc_trace(mVcdFile, grp_fu_232_p0, "grp_fu_232_p0");
    sc_trace(mVcdFile, grp_fu_232_p1, "grp_fu_232_p1");
    sc_trace(mVcdFile, grp_fu_238_p0, "grp_fu_238_p0");
    sc_trace(mVcdFile, grp_fu_241_p0, "grp_fu_241_p0");
    sc_trace(mVcdFile, grp_fu_232_p2, "grp_fu_232_p2");
    sc_trace(mVcdFile, grp_fu_219_opcode, "grp_fu_219_opcode");
    sc_trace(mVcdFile, grp_fu_219_ce, "grp_fu_219_ce");
    sc_trace(mVcdFile, grp_fu_223_ce, "grp_fu_223_ce");
    sc_trace(mVcdFile, grp_fu_228_ce, "grp_fu_228_ce");
    sc_trace(mVcdFile, grp_fu_232_ce, "grp_fu_232_ce");
    sc_trace(mVcdFile, grp_fu_232_opcode, "grp_fu_232_opcode");
    sc_trace(mVcdFile, grp_fu_238_ce, "grp_fu_238_ce");
    sc_trace(mVcdFile, grp_fu_241_ce, "grp_fu_241_ce");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, sum_of_squares_split_addr_8_reg_3600, "sum_of_squares_split_addr_8_reg_3600");

    }
}

distance_squared::~distance_squared() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void distance_squared::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st0_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
             !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
             !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_258_p2.read()))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
        } else if (esl_seteq<1,6,6>(ap_ST_st4_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
             !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
             esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_258_p2.read()))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_1;
        } else if ((esl_seteq<1,6,6>(ap_ST_st4_fsm_4, ap_CS_fsm.read()) || 
                    (esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
                     !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
                     !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_258_p2.read())))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it10 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
             !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
            ap_reg_ppiten_pp0_it10 = ap_reg_ppiten_pp0_it9.read();
        } else if (esl_seteq<1,6,6>(ap_ST_st4_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it10 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it11 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
             !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
            ap_reg_ppiten_pp0_it11 = ap_reg_ppiten_pp0_it10.read();
        } else if (esl_seteq<1,6,6>(ap_ST_st4_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it11 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it12 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
             !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
            ap_reg_ppiten_pp0_it12 = ap_reg_ppiten_pp0_it11.read();
        } else if (esl_seteq<1,6,6>(ap_ST_st4_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it12 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it13 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
             !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
            ap_reg_ppiten_pp0_it13 = ap_reg_ppiten_pp0_it12.read();
        } else if (esl_seteq<1,6,6>(ap_ST_st4_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it13 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it14 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
             !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
            ap_reg_ppiten_pp0_it14 = ap_reg_ppiten_pp0_it13.read();
        } else if (esl_seteq<1,6,6>(ap_ST_st4_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it14 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it15 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
             !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
            ap_reg_ppiten_pp0_it15 = ap_reg_ppiten_pp0_it14.read();
        } else if (esl_seteq<1,6,6>(ap_ST_st4_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it15 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it16 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
             !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
            ap_reg_ppiten_pp0_it16 = ap_reg_ppiten_pp0_it15.read();
        } else if (esl_seteq<1,6,6>(ap_ST_st4_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it16 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it17 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
             !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
            ap_reg_ppiten_pp0_it17 = ap_reg_ppiten_pp0_it16.read();
        } else if (esl_seteq<1,6,6>(ap_ST_st4_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it17 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it18 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
             !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
            ap_reg_ppiten_pp0_it18 = ap_reg_ppiten_pp0_it17.read();
        } else if (esl_seteq<1,6,6>(ap_ST_st4_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it18 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it19 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
             !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
            ap_reg_ppiten_pp0_it19 = ap_reg_ppiten_pp0_it18.read();
        } else if (esl_seteq<1,6,6>(ap_ST_st4_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it19 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it2 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
             !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
            ap_reg_ppiten_pp0_it2 = ap_reg_ppiten_pp0_it1.read();
        } else if (esl_seteq<1,6,6>(ap_ST_st4_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it2 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it20 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
             !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
            ap_reg_ppiten_pp0_it20 = ap_reg_ppiten_pp0_it19.read();
        } else if (esl_seteq<1,6,6>(ap_ST_st4_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it20 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it21 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
             !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
            ap_reg_ppiten_pp0_it21 = ap_reg_ppiten_pp0_it20.read();
        } else if (esl_seteq<1,6,6>(ap_ST_st4_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it21 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it22 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
             !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
            ap_reg_ppiten_pp0_it22 = ap_reg_ppiten_pp0_it21.read();
        } else if (esl_seteq<1,6,6>(ap_ST_st4_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it22 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it3 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
             !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
            ap_reg_ppiten_pp0_it3 = ap_reg_ppiten_pp0_it2.read();
        } else if (esl_seteq<1,6,6>(ap_ST_st4_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it3 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it4 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
             !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
            ap_reg_ppiten_pp0_it4 = ap_reg_ppiten_pp0_it3.read();
        } else if (esl_seteq<1,6,6>(ap_ST_st4_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it4 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it5 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
             !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
            ap_reg_ppiten_pp0_it5 = ap_reg_ppiten_pp0_it4.read();
        } else if (esl_seteq<1,6,6>(ap_ST_st4_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it5 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it6 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
             !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
            ap_reg_ppiten_pp0_it6 = ap_reg_ppiten_pp0_it5.read();
        } else if (esl_seteq<1,6,6>(ap_ST_st4_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it6 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it7 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
             !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
            ap_reg_ppiten_pp0_it7 = ap_reg_ppiten_pp0_it6.read();
        } else if (esl_seteq<1,6,6>(ap_ST_st4_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it7 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it8 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
             !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
            ap_reg_ppiten_pp0_it8 = ap_reg_ppiten_pp0_it7.read();
        } else if (esl_seteq<1,6,6>(ap_ST_st4_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it8 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it9 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
             !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
            ap_reg_ppiten_pp0_it9 = ap_reg_ppiten_pp0_it8.read();
        } else if (esl_seteq<1,6,6>(ap_ST_st4_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it9 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_dim_cast2_reg_335_pp0_it1 = dim_cast2_reg_335.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_dim_cast2_reg_335_pp0_it10 = ap_reg_ppstg_dim_cast2_reg_335_pp0_it9.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_dim_cast2_reg_335_pp0_it11 = ap_reg_ppstg_dim_cast2_reg_335_pp0_it10.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_dim_cast2_reg_335_pp0_it12 = ap_reg_ppstg_dim_cast2_reg_335_pp0_it11.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_dim_cast2_reg_335_pp0_it13 = ap_reg_ppstg_dim_cast2_reg_335_pp0_it12.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_dim_cast2_reg_335_pp0_it14 = ap_reg_ppstg_dim_cast2_reg_335_pp0_it13.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_dim_cast2_reg_335_pp0_it2 = ap_reg_ppstg_dim_cast2_reg_335_pp0_it1.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_dim_cast2_reg_335_pp0_it3 = ap_reg_ppstg_dim_cast2_reg_335_pp0_it2.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_dim_cast2_reg_335_pp0_it4 = ap_reg_ppstg_dim_cast2_reg_335_pp0_it3.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_dim_cast2_reg_335_pp0_it5 = ap_reg_ppstg_dim_cast2_reg_335_pp0_it4.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_dim_cast2_reg_335_pp0_it6 = ap_reg_ppstg_dim_cast2_reg_335_pp0_it5.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_dim_cast2_reg_335_pp0_it7 = ap_reg_ppstg_dim_cast2_reg_335_pp0_it6.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_dim_cast2_reg_335_pp0_it8 = ap_reg_ppstg_dim_cast2_reg_335_pp0_it7.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_dim_cast2_reg_335_pp0_it9 = ap_reg_ppstg_dim_cast2_reg_335_pp0_it8.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_exitcond1_reg_326_pp0_it1 = exitcond1_reg_326.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_exitcond1_reg_326_pp0_it10 = ap_reg_ppstg_exitcond1_reg_326_pp0_it9.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_exitcond1_reg_326_pp0_it11 = ap_reg_ppstg_exitcond1_reg_326_pp0_it10.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_exitcond1_reg_326_pp0_it12 = ap_reg_ppstg_exitcond1_reg_326_pp0_it11.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_exitcond1_reg_326_pp0_it13 = ap_reg_ppstg_exitcond1_reg_326_pp0_it12.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_exitcond1_reg_326_pp0_it14 = ap_reg_ppstg_exitcond1_reg_326_pp0_it13.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_exitcond1_reg_326_pp0_it15 = ap_reg_ppstg_exitcond1_reg_326_pp0_it14.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_exitcond1_reg_326_pp0_it16 = ap_reg_ppstg_exitcond1_reg_326_pp0_it15.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_exitcond1_reg_326_pp0_it17 = ap_reg_ppstg_exitcond1_reg_326_pp0_it16.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_exitcond1_reg_326_pp0_it18 = ap_reg_ppstg_exitcond1_reg_326_pp0_it17.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_exitcond1_reg_326_pp0_it19 = ap_reg_ppstg_exitcond1_reg_326_pp0_it18.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_exitcond1_reg_326_pp0_it2 = ap_reg_ppstg_exitcond1_reg_326_pp0_it1.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_exitcond1_reg_326_pp0_it20 = ap_reg_ppstg_exitcond1_reg_326_pp0_it19.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_exitcond1_reg_326_pp0_it21 = ap_reg_ppstg_exitcond1_reg_326_pp0_it20.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_exitcond1_reg_326_pp0_it3 = ap_reg_ppstg_exitcond1_reg_326_pp0_it2.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_exitcond1_reg_326_pp0_it4 = ap_reg_ppstg_exitcond1_reg_326_pp0_it3.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_exitcond1_reg_326_pp0_it5 = ap_reg_ppstg_exitcond1_reg_326_pp0_it4.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_exitcond1_reg_326_pp0_it6 = ap_reg_ppstg_exitcond1_reg_326_pp0_it5.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_exitcond1_reg_326_pp0_it7 = ap_reg_ppstg_exitcond1_reg_326_pp0_it6.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_exitcond1_reg_326_pp0_it8 = ap_reg_ppstg_exitcond1_reg_326_pp0_it7.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_exitcond1_reg_326_pp0_it9 = ap_reg_ppstg_exitcond1_reg_326_pp0_it8.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_sum_of_squares_split_addr_8_reg_360_pp0_it16 = sum_of_squares_split_addr_8_reg_360.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_sum_of_squares_split_addr_8_reg_360_pp0_it17 = ap_reg_ppstg_sum_of_squares_split_addr_8_reg_360_pp0_it16.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_sum_of_squares_split_addr_8_reg_360_pp0_it18 = ap_reg_ppstg_sum_of_squares_split_addr_8_reg_360_pp0_it17.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_sum_of_squares_split_addr_8_reg_360_pp0_it19 = ap_reg_ppstg_sum_of_squares_split_addr_8_reg_360_pp0_it18.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_sum_of_squares_split_addr_8_reg_360_pp0_it20 = ap_reg_ppstg_sum_of_squares_split_addr_8_reg_360_pp0_it19.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_sum_of_squares_split_addr_8_reg_360_pp0_it21 = ap_reg_ppstg_sum_of_squares_split_addr_8_reg_360_pp0_it20.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it16.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it15.read()))) {
        diff_squared_reg_366 = grp_fu_228_p2.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_258_p2.read()))) {
        dim_cast2_reg_335 = dim_reg_207.read().range(3-1, 0);
    }
    if (esl_seteq<1,6,6>(ap_ST_st4_fsm_4, ap_CS_fsm.read())) {
        dim_reg_207 = ap_const_lv8_0;
    } else if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
                !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_258_p2.read()))) {
        dim_reg_207 = (!dim_reg_207.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_bigint<8>(dim_reg_207.read()) + sc_biguint<8>(ap_const_lv8_1));
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        exitcond1_reg_326 = (!dim_reg_207.read().is_01() || !ap_const_lv8_C8.is_01())? sc_lv<1>(): sc_lv<1>(dim_reg_207.read() == ap_const_lv8_C8);
    }
    if (((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it10.read()) && 
          !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it9.read())) || 
         esl_seteq<1,6,6>(ap_ST_st36_fsm_14, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st41_fsm_19, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st46_fsm_24, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st51_fsm_29, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st56_fsm_34, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st61_fsm_39, ap_CS_fsm.read()))) {
        reg_244 = grp_fu_219_p2.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_st36_fsm_14, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st41_fsm_19, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st46_fsm_24, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st51_fsm_29, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st56_fsm_34, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st61_fsm_39, ap_CS_fsm.read()) || 
         (esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it16.read()) && 
          !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it15.read())) || 
         esl_seteq<1,6,6>(ap_ST_st29_fsm_7, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st31_fsm_9, ap_CS_fsm.read()))) {
        reg_251 = sum_of_squares_split_q0.read();
    }
    if (esl_seteq<1,6,6>(ap_ST_st31_fsm_9, ap_CS_fsm.read())) {
        sum_of_squares_reg_376 = (!grp_fu_232_p2.read()[0].is_01())? sc_lv<64>(): ((grp_fu_232_p2.read()[0].to_bool())? ap_const_lv64_0: reg_251.read());
    }
    if (esl_seteq<1,6,6>(ap_ST_st1_fsm_1, ap_CS_fsm.read())) {
        sum_of_squares_split_addr_1_reg_291 = sum_of_squares_split_addr_1_gep_fu_139_p3.read();
    }
    if (esl_seteq<1,6,6>(ap_ST_st2_fsm_2, ap_CS_fsm.read())) {
        sum_of_squares_split_addr_2_reg_296 = sum_of_squares_split_addr_2_gep_fu_152_p3.read();
    }
    if (esl_seteq<1,6,6>(ap_ST_st2_fsm_2, ap_CS_fsm.read())) {
        sum_of_squares_split_addr_3_reg_301 = sum_of_squares_split_addr_3_gep_fu_160_p3.read();
    }
    if (esl_seteq<1,6,6>(ap_ST_st3_fsm_3, ap_CS_fsm.read())) {
        sum_of_squares_split_addr_4_reg_306 = sum_of_squares_split_addr_4_gep_fu_168_p3.read();
    }
    if (esl_seteq<1,6,6>(ap_ST_st3_fsm_3, ap_CS_fsm.read())) {
        sum_of_squares_split_addr_5_reg_311 = sum_of_squares_split_addr_5_gep_fu_176_p3.read();
    }
    if (esl_seteq<1,6,6>(ap_ST_st4_fsm_4, ap_CS_fsm.read())) {
        sum_of_squares_split_addr_6_reg_316 = sum_of_squares_split_addr_6_gep_fu_184_p3.read();
    }
    if (esl_seteq<1,6,6>(ap_ST_st4_fsm_4, ap_CS_fsm.read())) {
        sum_of_squares_split_addr_7_reg_321 = sum_of_squares_split_addr_7_gep_fu_192_p3.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it15.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it14.read()))) {
        sum_of_squares_split_addr_8_reg_360 =  (sc_lv<3>) (sum_of_squares_split_addr_8_reg_3600.read());
    }
    if (esl_seteq<1,6,6>(ap_ST_st1_fsm_1, ap_CS_fsm.read())) {
        sum_of_squares_split_addr_reg_286 = sum_of_squares_split_addr_gep_fu_125_p3.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it21.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it20.read()))) {
        tmp_3_reg_371 = grp_fu_223_p2.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(exitcond1_reg_326.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        vector1_data_V_read_reg_340 = vector1_data_V_dout.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it4.read()))) {
        vector1_data_reg_350 = grp_fu_238_p1.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(exitcond1_reg_326.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        vector2_data_V_read_reg_345 = vector2_data_V_dout.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it4.read()))) {
        vector2_data_reg_355 = grp_fu_241_p1.read();
    }
}

void distance_squared::thread_ap_NS_fsm() {
    if (((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it22.read()) && 
          !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
          !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it21.read())) || 
         (esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_258_p2.read()) && 
          !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_NS_fsm = ap_ST_st28_fsm_6;
    } else if ((esl_seteq<1,6,6>(ap_ST_st66_fsm_44, ap_CS_fsm.read()) && 
                !esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()))) {
        ap_NS_fsm = ap_ST_st0_fsm_0;
    } else if (esl_seteq<1,6,6>(ap_ST_st65_fsm_43, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st66_fsm_44;
    } else if (esl_seteq<1,6,6>(ap_ST_st64_fsm_42, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st65_fsm_43;
    } else if (esl_seteq<1,6,6>(ap_ST_st63_fsm_41, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st64_fsm_42;
    } else if (esl_seteq<1,6,6>(ap_ST_st62_fsm_40, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st63_fsm_41;
    } else if (esl_seteq<1,6,6>(ap_ST_st61_fsm_39, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st62_fsm_40;
    } else if (esl_seteq<1,6,6>(ap_ST_st60_fsm_38, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st61_fsm_39;
    } else if (esl_seteq<1,6,6>(ap_ST_st59_fsm_37, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st60_fsm_38;
    } else if (esl_seteq<1,6,6>(ap_ST_st58_fsm_36, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st59_fsm_37;
    } else if (esl_seteq<1,6,6>(ap_ST_st57_fsm_35, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st58_fsm_36;
    } else if (esl_seteq<1,6,6>(ap_ST_st56_fsm_34, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st57_fsm_35;
    } else if (esl_seteq<1,6,6>(ap_ST_st55_fsm_33, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st56_fsm_34;
    } else if (esl_seteq<1,6,6>(ap_ST_st54_fsm_32, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st55_fsm_33;
    } else if (esl_seteq<1,6,6>(ap_ST_st53_fsm_31, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st54_fsm_32;
    } else if (esl_seteq<1,6,6>(ap_ST_st52_fsm_30, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st53_fsm_31;
    } else if (esl_seteq<1,6,6>(ap_ST_st51_fsm_29, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st52_fsm_30;
    } else if (esl_seteq<1,6,6>(ap_ST_st50_fsm_28, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st51_fsm_29;
    } else if (esl_seteq<1,6,6>(ap_ST_st49_fsm_27, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st50_fsm_28;
    } else if (esl_seteq<1,6,6>(ap_ST_st48_fsm_26, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st49_fsm_27;
    } else if (esl_seteq<1,6,6>(ap_ST_st47_fsm_25, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st48_fsm_26;
    } else if (esl_seteq<1,6,6>(ap_ST_st46_fsm_24, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st47_fsm_25;
    } else if (esl_seteq<1,6,6>(ap_ST_st45_fsm_23, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st46_fsm_24;
    } else if (esl_seteq<1,6,6>(ap_ST_st44_fsm_22, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st45_fsm_23;
    } else if (esl_seteq<1,6,6>(ap_ST_st43_fsm_21, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st44_fsm_22;
    } else if (esl_seteq<1,6,6>(ap_ST_st42_fsm_20, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st43_fsm_21;
    } else if (esl_seteq<1,6,6>(ap_ST_st41_fsm_19, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st42_fsm_20;
    } else if (esl_seteq<1,6,6>(ap_ST_st40_fsm_18, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st41_fsm_19;
    } else if (esl_seteq<1,6,6>(ap_ST_st39_fsm_17, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st40_fsm_18;
    } else if (esl_seteq<1,6,6>(ap_ST_st38_fsm_16, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st39_fsm_17;
    } else if (esl_seteq<1,6,6>(ap_ST_st37_fsm_15, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st38_fsm_16;
    } else if (esl_seteq<1,6,6>(ap_ST_st36_fsm_14, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st37_fsm_15;
    } else if (esl_seteq<1,6,6>(ap_ST_st35_fsm_13, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st36_fsm_14;
    } else if (esl_seteq<1,6,6>(ap_ST_st34_fsm_12, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st35_fsm_13;
    } else if (esl_seteq<1,6,6>(ap_ST_st33_fsm_11, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st34_fsm_12;
    } else if (esl_seteq<1,6,6>(ap_ST_st32_fsm_10, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st33_fsm_11;
    } else if (esl_seteq<1,6,6>(ap_ST_st31_fsm_9, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st32_fsm_10;
    } else if (esl_seteq<1,6,6>(ap_ST_st30_fsm_8, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st31_fsm_9;
    } else if (esl_seteq<1,6,6>(ap_ST_st29_fsm_7, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st30_fsm_8;
    } else if (esl_seteq<1,6,6>(ap_ST_st28_fsm_6, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st29_fsm_7;
    } else if (esl_seteq<1,6,6>(ap_ST_st4_fsm_4, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_pp0_stg0_fsm_5;
    } else if (esl_seteq<1,6,6>(ap_ST_st3_fsm_3, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st4_fsm_4;
    } else if (esl_seteq<1,6,6>(ap_ST_st2_fsm_2, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st3_fsm_3;
    } else if (esl_seteq<1,6,6>(ap_ST_st1_fsm_1, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st2_fsm_2;
    } else if (((esl_seteq<1,6,6>(ap_ST_st0_fsm_0, ap_CS_fsm.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read())) || 
                (esl_seteq<1,6,6>(ap_ST_st66_fsm_44, ap_CS_fsm.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read())))) {
        ap_NS_fsm = ap_ST_st1_fsm_1;
    } else {
        ap_NS_fsm = ap_CS_fsm.read();
    }
}

void distance_squared::thread_ap_done() {
    if (esl_seteq<1,6,6>(ap_ST_st66_fsm_44, ap_CS_fsm.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void distance_squared::thread_ap_idle() {
    if (esl_seteq<1,6,6>(ap_ST_st0_fsm_0, ap_CS_fsm.read())) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void distance_squared::thread_ap_sig_bdd_100() {
    ap_sig_bdd_100 = ((esl_seteq<1,1,1>(vector1_data_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(exitcond1_reg_326.read(), ap_const_lv1_0)) || (esl_seteq<1,1,1>(exitcond1_reg_326.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(vector2_data_V_empty_n.read(), ap_const_logic_0)));
}

void distance_squared::thread_exitcond1_fu_258_p2() {
    exitcond1_fu_258_p2 = (!dim_reg_207.read().is_01() || !ap_const_lv8_C8.is_01())? sc_lv<1>(): sc_lv<1>(dim_reg_207.read() == ap_const_lv8_C8);
}

void distance_squared::thread_grp_fu_219_ce() {
    if ((esl_seteq<1,6,6>(ap_ST_st0_fsm_0, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st29_fsm_7, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st31_fsm_9, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st1_fsm_1, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st2_fsm_2, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st3_fsm_3, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st4_fsm_4, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st28_fsm_6, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st30_fsm_8, ap_CS_fsm.read()) || 
         (esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
          ((ap_sig_bdd_100.read() && 
            esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || 
           (!esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it5.read()) && 
            !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it6.read()) && 
            !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it7.read()) && 
            !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it8.read()) && 
            !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it9.read())))))) {
        grp_fu_219_ce = ap_const_logic_0;
    } else {
        grp_fu_219_ce = ap_const_logic_1;
    }
}

void distance_squared::thread_grp_fu_219_opcode() {
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it6.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it5.read()))) {
        grp_fu_219_opcode = ap_const_lv2_1;
    } else if ((esl_seteq<1,6,6>(ap_ST_st32_fsm_10, ap_CS_fsm.read()) || 
                esl_seteq<1,6,6>(ap_ST_st37_fsm_15, ap_CS_fsm.read()) || 
                esl_seteq<1,6,6>(ap_ST_st42_fsm_20, ap_CS_fsm.read()) || 
                esl_seteq<1,6,6>(ap_ST_st47_fsm_25, ap_CS_fsm.read()) || 
                esl_seteq<1,6,6>(ap_ST_st52_fsm_30, ap_CS_fsm.read()) || 
                esl_seteq<1,6,6>(ap_ST_st57_fsm_35, ap_CS_fsm.read()) || 
                esl_seteq<1,6,6>(ap_ST_st62_fsm_40, ap_CS_fsm.read()))) {
        grp_fu_219_opcode = ap_const_lv2_0;
    } else {
        grp_fu_219_opcode = ap_const_lv2_1;
    }
}

void distance_squared::thread_grp_fu_219_p0() {
    if ((esl_seteq<1,6,6>(ap_ST_st32_fsm_10, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st37_fsm_15, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st42_fsm_20, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st47_fsm_25, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st52_fsm_30, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st57_fsm_35, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st62_fsm_40, ap_CS_fsm.read()))) {
        grp_fu_219_p0 = reg_251.read();
    } else if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it5.read()))) {
        grp_fu_219_p0 = vector1_data_reg_350.read();
    } else {
        grp_fu_219_p0 = vector1_data_reg_350.read();
    }
}

void distance_squared::thread_grp_fu_219_p1() {
    if ((esl_seteq<1,6,6>(ap_ST_st37_fsm_15, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st42_fsm_20, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st47_fsm_25, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st52_fsm_30, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st57_fsm_35, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st62_fsm_40, ap_CS_fsm.read()))) {
        grp_fu_219_p1 = reg_244.read();
    } else if (esl_seteq<1,6,6>(ap_ST_st32_fsm_10, ap_CS_fsm.read())) {
        grp_fu_219_p1 = sum_of_squares_reg_376.read();
    } else if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it5.read()))) {
        grp_fu_219_p1 = vector2_data_reg_355.read();
    } else {
        grp_fu_219_p1 = sum_of_squares_reg_376.read();
    }
}

void distance_squared::thread_grp_fu_223_ce() {
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
         (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it20.read()) || 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it16.read()) || 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it17.read()) || 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it18.read()) || 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it19.read())))) {
        grp_fu_223_ce = ap_const_logic_1;
    } else {
        grp_fu_223_ce = ap_const_logic_0;
    }
}

void distance_squared::thread_grp_fu_223_p0() {
    grp_fu_223_p0 = reg_251.read();
}

void distance_squared::thread_grp_fu_223_p1() {
    grp_fu_223_p1 = diff_squared_reg_366.read();
}

void distance_squared::thread_grp_fu_228_ce() {
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
         (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it15.read()) || 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it14.read()) || 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it10.read()) || 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it11.read()) || 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it12.read()) || 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it13.read())))) {
        grp_fu_228_ce = ap_const_logic_1;
    } else {
        grp_fu_228_ce = ap_const_logic_0;
    }
}

void distance_squared::thread_grp_fu_228_p0() {
    grp_fu_228_p0 = reg_244.read();
}

void distance_squared::thread_grp_fu_228_p1() {
    grp_fu_228_p1 = reg_244.read();
}

void distance_squared::thread_grp_fu_232_ce() {
    grp_fu_232_ce = ap_const_logic_1;
}

void distance_squared::thread_grp_fu_232_opcode() {
    grp_fu_232_opcode = ap_const_lv5_1;
}

void distance_squared::thread_grp_fu_232_p0() {
    grp_fu_232_p0 = sum_of_squares_split_q0.read();
}

void distance_squared::thread_grp_fu_232_p1() {
    grp_fu_232_p1 = ap_const_lv64_8000000000000000;
}

void distance_squared::thread_grp_fu_238_ce() {
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
         (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it4.read()) || 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it1.read()) || 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it2.read()) || 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it3.read())))) {
        grp_fu_238_ce = ap_const_logic_1;
    } else {
        grp_fu_238_ce = ap_const_logic_0;
    }
}

void distance_squared::thread_grp_fu_238_p0() {
    grp_fu_238_p0 = vector1_data_V_read_reg_340.read();
}

void distance_squared::thread_grp_fu_241_ce() {
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
         (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it4.read()) || 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it1.read()) || 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it2.read()) || 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it3.read())))) {
        grp_fu_241_ce = ap_const_logic_1;
    } else {
        grp_fu_241_ce = ap_const_logic_0;
    }
}

void distance_squared::thread_grp_fu_241_p0() {
    grp_fu_241_p0 = vector2_data_V_read_reg_345.read();
}

void distance_squared::thread_sum() {
    sum = grp_fu_219_p2.read();
}

void distance_squared::thread_sum_of_squares_split_addr_1_gep_fu_139_p3() {
    sum_of_squares_split_addr_1_gep_fu_139_p3 =  (sc_lv<3>) (ap_const_lv64_1);
}

void distance_squared::thread_sum_of_squares_split_addr_2_gep_fu_152_p3() {
    sum_of_squares_split_addr_2_gep_fu_152_p3 =  (sc_lv<3>) (ap_const_lv64_2);
}

void distance_squared::thread_sum_of_squares_split_addr_3_gep_fu_160_p3() {
    sum_of_squares_split_addr_3_gep_fu_160_p3 =  (sc_lv<3>) (ap_const_lv64_3);
}

void distance_squared::thread_sum_of_squares_split_addr_4_gep_fu_168_p3() {
    sum_of_squares_split_addr_4_gep_fu_168_p3 =  (sc_lv<3>) (ap_const_lv64_4);
}

void distance_squared::thread_sum_of_squares_split_addr_5_gep_fu_176_p3() {
    sum_of_squares_split_addr_5_gep_fu_176_p3 =  (sc_lv<3>) (ap_const_lv64_5);
}

void distance_squared::thread_sum_of_squares_split_addr_6_gep_fu_184_p3() {
    sum_of_squares_split_addr_6_gep_fu_184_p3 =  (sc_lv<3>) (ap_const_lv64_6);
}

void distance_squared::thread_sum_of_squares_split_addr_7_gep_fu_192_p3() {
    sum_of_squares_split_addr_7_gep_fu_192_p3 =  (sc_lv<3>) (ap_const_lv64_7);
}

void distance_squared::thread_sum_of_squares_split_addr_8_reg_3600() {
    sum_of_squares_split_addr_8_reg_3600 = esl_zext<64,3>(ap_reg_ppstg_dim_cast2_reg_335_pp0_it14.read());
}

void distance_squared::thread_sum_of_squares_split_addr_gep_fu_125_p3() {
    sum_of_squares_split_addr_gep_fu_125_p3 =  (sc_lv<3>) (ap_const_lv64_0);
}

void distance_squared::thread_sum_of_squares_split_address0() {
    if (esl_seteq<1,6,6>(ap_ST_st4_fsm_4, ap_CS_fsm.read())) {
        sum_of_squares_split_address0 =  (sc_lv<3>) (ap_const_lv64_6);
    } else if (esl_seteq<1,6,6>(ap_ST_st3_fsm_3, ap_CS_fsm.read())) {
        sum_of_squares_split_address0 =  (sc_lv<3>) (ap_const_lv64_4);
    } else if (esl_seteq<1,6,6>(ap_ST_st2_fsm_2, ap_CS_fsm.read())) {
        sum_of_squares_split_address0 =  (sc_lv<3>) (ap_const_lv64_2);
    } else if (esl_seteq<1,6,6>(ap_ST_st1_fsm_1, ap_CS_fsm.read())) {
        sum_of_squares_split_address0 =  (sc_lv<3>) (ap_const_lv64_0);
    } else if (esl_seteq<1,6,6>(ap_ST_st60_fsm_38, ap_CS_fsm.read())) {
        sum_of_squares_split_address0 = sum_of_squares_split_addr_7_reg_321.read();
    } else if (esl_seteq<1,6,6>(ap_ST_st55_fsm_33, ap_CS_fsm.read())) {
        sum_of_squares_split_address0 = sum_of_squares_split_addr_6_reg_316.read();
    } else if (esl_seteq<1,6,6>(ap_ST_st50_fsm_28, ap_CS_fsm.read())) {
        sum_of_squares_split_address0 = sum_of_squares_split_addr_5_reg_311.read();
    } else if (esl_seteq<1,6,6>(ap_ST_st45_fsm_23, ap_CS_fsm.read())) {
        sum_of_squares_split_address0 = sum_of_squares_split_addr_4_reg_306.read();
    } else if (esl_seteq<1,6,6>(ap_ST_st40_fsm_18, ap_CS_fsm.read())) {
        sum_of_squares_split_address0 = sum_of_squares_split_addr_3_reg_301.read();
    } else if (esl_seteq<1,6,6>(ap_ST_st35_fsm_13, ap_CS_fsm.read())) {
        sum_of_squares_split_address0 = sum_of_squares_split_addr_2_reg_296.read();
    } else if (esl_seteq<1,6,6>(ap_ST_st30_fsm_8, ap_CS_fsm.read())) {
        sum_of_squares_split_address0 = sum_of_squares_split_addr_1_reg_291.read();
    } else if (esl_seteq<1,6,6>(ap_ST_st28_fsm_6, ap_CS_fsm.read())) {
        sum_of_squares_split_address0 = sum_of_squares_split_addr_reg_286.read();
    } else if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it15.read()) && 
                !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it14.read()))) {
        sum_of_squares_split_address0 =  (sc_lv<3>) (tmp_2_fu_274_p1.read());
    } else {
        sum_of_squares_split_address0 =  (sc_lv<3>) (tmp_2_fu_274_p1.read());
    }
}

void distance_squared::thread_sum_of_squares_split_address1() {
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it22.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it21.read()))) {
        sum_of_squares_split_address1 = ap_reg_ppstg_sum_of_squares_split_addr_8_reg_360_pp0_it21.read();
    } else if (esl_seteq<1,6,6>(ap_ST_st4_fsm_4, ap_CS_fsm.read())) {
        sum_of_squares_split_address1 =  (sc_lv<3>) (ap_const_lv64_7);
    } else if (esl_seteq<1,6,6>(ap_ST_st3_fsm_3, ap_CS_fsm.read())) {
        sum_of_squares_split_address1 =  (sc_lv<3>) (ap_const_lv64_5);
    } else if (esl_seteq<1,6,6>(ap_ST_st2_fsm_2, ap_CS_fsm.read())) {
        sum_of_squares_split_address1 =  (sc_lv<3>) (ap_const_lv64_3);
    } else if (esl_seteq<1,6,6>(ap_ST_st1_fsm_1, ap_CS_fsm.read())) {
        sum_of_squares_split_address1 =  (sc_lv<3>) (ap_const_lv64_1);
    } else {
        sum_of_squares_split_address1 = ap_reg_ppstg_sum_of_squares_split_addr_8_reg_360_pp0_it21.read();
    }
}

void distance_squared::thread_sum_of_squares_split_ce0() {
    if ((esl_seteq<1,6,6>(ap_ST_st1_fsm_1, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st2_fsm_2, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st3_fsm_3, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st4_fsm_4, ap_CS_fsm.read()) || 
         (esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it15.read()) && 
          !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it14.read())) || 
         esl_seteq<1,6,6>(ap_ST_st28_fsm_6, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st30_fsm_8, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st35_fsm_13, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st40_fsm_18, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st45_fsm_23, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st50_fsm_28, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st55_fsm_33, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st60_fsm_38, ap_CS_fsm.read()))) {
        sum_of_squares_split_ce0 = ap_const_logic_1;
    } else {
        sum_of_squares_split_ce0 = ap_const_logic_0;
    }
}

void distance_squared::thread_sum_of_squares_split_ce1() {
    if ((esl_seteq<1,6,6>(ap_ST_st1_fsm_1, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st2_fsm_2, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st3_fsm_3, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st4_fsm_4, ap_CS_fsm.read()) || 
         (esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it22.read()) && 
          !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it21.read())))) {
        sum_of_squares_split_ce1 = ap_const_logic_1;
    } else {
        sum_of_squares_split_ce1 = ap_const_logic_0;
    }
}

void distance_squared::thread_sum_of_squares_split_d0() {
    sum_of_squares_split_d0 = ap_const_lv64_0;
}

void distance_squared::thread_sum_of_squares_split_d1() {
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it22.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it21.read()))) {
        sum_of_squares_split_d1 = tmp_3_reg_371.read();
    } else if ((esl_seteq<1,6,6>(ap_ST_st1_fsm_1, ap_CS_fsm.read()) || 
                esl_seteq<1,6,6>(ap_ST_st2_fsm_2, ap_CS_fsm.read()) || 
                esl_seteq<1,6,6>(ap_ST_st3_fsm_3, ap_CS_fsm.read()) || 
                esl_seteq<1,6,6>(ap_ST_st4_fsm_4, ap_CS_fsm.read()))) {
        sum_of_squares_split_d1 = ap_const_lv64_0;
    } else {
        sum_of_squares_split_d1 = ap_const_lv64_0;
    }
}

void distance_squared::thread_sum_of_squares_split_we0() {
    if ((esl_seteq<1,6,6>(ap_ST_st1_fsm_1, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st2_fsm_2, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st3_fsm_3, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st4_fsm_4, ap_CS_fsm.read()))) {
        sum_of_squares_split_we0 = ap_const_logic_1;
    } else {
        sum_of_squares_split_we0 = ap_const_logic_0;
    }
}

void distance_squared::thread_sum_of_squares_split_we1() {
    if ((esl_seteq<1,6,6>(ap_ST_st1_fsm_1, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st2_fsm_2, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st3_fsm_3, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st4_fsm_4, ap_CS_fsm.read()) || 
         (esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it22.read()) && 
          !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_326_pp0_it21.read())))) {
        sum_of_squares_split_we1 = ap_const_logic_1;
    } else {
        sum_of_squares_split_we1 = ap_const_logic_0;
    }
}

void distance_squared::thread_tmp_2_fu_274_p1() {
    tmp_2_fu_274_p1 = esl_zext<64,3>(ap_reg_ppstg_dim_cast2_reg_335_pp0_it14.read());
}

void distance_squared::thread_vector1_data_V_read() {
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(exitcond1_reg_326.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        vector1_data_V_read = ap_const_logic_1;
    } else {
        vector1_data_V_read = ap_const_logic_0;
    }
}

void distance_squared::thread_vector1_keep_V_read() {
    vector1_keep_V_read = ap_const_logic_0;
}

void distance_squared::thread_vector1_last_V_read() {
    vector1_last_V_read = ap_const_logic_0;
}

void distance_squared::thread_vector2_data_V_read() {
    if ((esl_seteq<1,6,6>(ap_ST_pp0_stg0_fsm_5, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(exitcond1_reg_326.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_100.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        vector2_data_V_read = ap_const_logic_1;
    } else {
        vector2_data_V_read = ap_const_logic_0;
    }
}

void distance_squared::thread_vector2_keep_V_read() {
    vector2_keep_V_read = ap_const_logic_0;
}

void distance_squared::thread_vector2_last_V_read() {
    vector2_last_V_read = ap_const_logic_0;
}

void distance_squared::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (dump_tv && string(dump_tv) == "off") return;

    wait();

    ofstream mAeslHdltvinHandle("distance_squared.autohdltvin.dat");
    ofstream mAeslHdltvoutHandle("distance_squared.autohdltvout.dat");
    int ap_cycleNo = 0;
    while (1) {
        wait();
        mAeslHdltvinHandle << "[[cycle]] " << ap_cycleNo << endl;
        mAeslHdltvoutHandle << "[[cycle]] " << ap_cycleNo << endl;
        mAeslHdltvinHandle << "[ap_rst]" << endl;
        mAeslHdltvinHandle << ap_rst.read() << endl;
        mAeslHdltvinHandle << "[/ap_rst]" << endl;
        mAeslHdltvinHandle << "[ap_start]" << endl;
        mAeslHdltvinHandle << ap_start.read() << endl;
        mAeslHdltvinHandle << "[/ap_start]" << endl;
        mAeslHdltvoutHandle << "[ap_done]" << endl;
        mAeslHdltvoutHandle << ap_done.read() << endl;
        mAeslHdltvoutHandle << "[/ap_done]" << endl;
        mAeslHdltvoutHandle << "[ap_idle]" << endl;
        mAeslHdltvoutHandle << ap_idle.read() << endl;
        mAeslHdltvoutHandle << "[/ap_idle]" << endl;
        mAeslHdltvinHandle << "[vector1_data_V_dout]" << endl;
        mAeslHdltvinHandle << vector1_data_V_dout.read() << endl;
        mAeslHdltvinHandle << "[/vector1_data_V_dout]" << endl;
        mAeslHdltvinHandle << "[vector1_data_V_empty_n]" << endl;
        mAeslHdltvinHandle << vector1_data_V_empty_n.read() << endl;
        mAeslHdltvinHandle << "[/vector1_data_V_empty_n]" << endl;
        mAeslHdltvoutHandle << "[vector1_data_V_read]" << endl;
        mAeslHdltvoutHandle << vector1_data_V_read.read() << endl;
        mAeslHdltvoutHandle << "[/vector1_data_V_read]" << endl;
        mAeslHdltvinHandle << "[vector1_keep_V_dout]" << endl;
        mAeslHdltvinHandle << vector1_keep_V_dout.read() << endl;
        mAeslHdltvinHandle << "[/vector1_keep_V_dout]" << endl;
        mAeslHdltvinHandle << "[vector1_keep_V_empty_n]" << endl;
        mAeslHdltvinHandle << vector1_keep_V_empty_n.read() << endl;
        mAeslHdltvinHandle << "[/vector1_keep_V_empty_n]" << endl;
        mAeslHdltvoutHandle << "[vector1_keep_V_read]" << endl;
        mAeslHdltvoutHandle << vector1_keep_V_read.read() << endl;
        mAeslHdltvoutHandle << "[/vector1_keep_V_read]" << endl;
        mAeslHdltvinHandle << "[vector1_last_V_dout]" << endl;
        mAeslHdltvinHandle << vector1_last_V_dout.read() << endl;
        mAeslHdltvinHandle << "[/vector1_last_V_dout]" << endl;
        mAeslHdltvinHandle << "[vector1_last_V_empty_n]" << endl;
        mAeslHdltvinHandle << vector1_last_V_empty_n.read() << endl;
        mAeslHdltvinHandle << "[/vector1_last_V_empty_n]" << endl;
        mAeslHdltvoutHandle << "[vector1_last_V_read]" << endl;
        mAeslHdltvoutHandle << vector1_last_V_read.read() << endl;
        mAeslHdltvoutHandle << "[/vector1_last_V_read]" << endl;
        mAeslHdltvinHandle << "[vector2_data_V_dout]" << endl;
        mAeslHdltvinHandle << vector2_data_V_dout.read() << endl;
        mAeslHdltvinHandle << "[/vector2_data_V_dout]" << endl;
        mAeslHdltvinHandle << "[vector2_data_V_empty_n]" << endl;
        mAeslHdltvinHandle << vector2_data_V_empty_n.read() << endl;
        mAeslHdltvinHandle << "[/vector2_data_V_empty_n]" << endl;
        mAeslHdltvoutHandle << "[vector2_data_V_read]" << endl;
        mAeslHdltvoutHandle << vector2_data_V_read.read() << endl;
        mAeslHdltvoutHandle << "[/vector2_data_V_read]" << endl;
        mAeslHdltvinHandle << "[vector2_keep_V_dout]" << endl;
        mAeslHdltvinHandle << vector2_keep_V_dout.read() << endl;
        mAeslHdltvinHandle << "[/vector2_keep_V_dout]" << endl;
        mAeslHdltvinHandle << "[vector2_keep_V_empty_n]" << endl;
        mAeslHdltvinHandle << vector2_keep_V_empty_n.read() << endl;
        mAeslHdltvinHandle << "[/vector2_keep_V_empty_n]" << endl;
        mAeslHdltvoutHandle << "[vector2_keep_V_read]" << endl;
        mAeslHdltvoutHandle << vector2_keep_V_read.read() << endl;
        mAeslHdltvoutHandle << "[/vector2_keep_V_read]" << endl;
        mAeslHdltvinHandle << "[vector2_last_V_dout]" << endl;
        mAeslHdltvinHandle << vector2_last_V_dout.read() << endl;
        mAeslHdltvinHandle << "[/vector2_last_V_dout]" << endl;
        mAeslHdltvinHandle << "[vector2_last_V_empty_n]" << endl;
        mAeslHdltvinHandle << vector2_last_V_empty_n.read() << endl;
        mAeslHdltvinHandle << "[/vector2_last_V_empty_n]" << endl;
        mAeslHdltvoutHandle << "[vector2_last_V_read]" << endl;
        mAeslHdltvoutHandle << vector2_last_V_read.read() << endl;
        mAeslHdltvoutHandle << "[/vector2_last_V_read]" << endl;
        mAeslHdltvoutHandle << "[sum]" << endl;
        mAeslHdltvoutHandle << sum.read() << endl;
        mAeslHdltvoutHandle << "[/sum]" << endl;
        mAeslHdltvinHandle << "[[/cycle]]" << endl;
        mAeslHdltvoutHandle << "[[/cycle]]" << endl;
        ap_cycleNo++;
    }
}

}

