// ==============================================================
// File generated by AutoESL - High-Level Synthesis System (C, C++, SystemC)
// Version: 2012.1
// Copyright (C) 2012 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __distance_squared_grp_fu_228_ACMP_dcmp_4__HH__
#define __distance_squared_grp_fu_228_ACMP_dcmp_4__HH__
#include "ACMP_dcmp.h"
#include <systemc>

template<
    int ID,
    int NUM_STAGE,
    int din0_WIDTH,
    int din1_WIDTH,
    int dout_WIDTH>
SC_MODULE(distance_squared_grp_fu_228_ACMP_dcmp_4) {
    sc_core::sc_in_clk clk;
    sc_core::sc_in<sc_dt::sc_logic> reset;
    sc_core::sc_in<sc_dt::sc_logic> ce;
    sc_core::sc_in< sc_dt::sc_lv<din0_WIDTH> >   din0;
    sc_core::sc_in< sc_dt::sc_lv<din1_WIDTH> >   din1;
    sc_core::sc_in< sc_dt::sc_lv<5> >   opcode;
    sc_core::sc_out< sc_dt::sc_lv<dout_WIDTH> >   dout;



    ACMP_dcmp<ID, 3, din0_WIDTH, din1_WIDTH, dout_WIDTH> ACMP_dcmp_U;

    SC_CTOR(distance_squared_grp_fu_228_ACMP_dcmp_4):  ACMP_dcmp_U ("ACMP_dcmp_U") {
        ACMP_dcmp_U.clk(clk);
        ACMP_dcmp_U.reset(reset);
        ACMP_dcmp_U.ce(ce);
        ACMP_dcmp_U.din0(din0);
        ACMP_dcmp_U.din1(din1);
        ACMP_dcmp_U.dout(dout);
        ACMP_dcmp_U.opcode(opcode);

    }

};

#endif //
