// ==============================================================
// RTL generated by AutoESL - High-Level Synthesis System (C, C++, SystemC)
// Version: 2012.1
// Copyright (C) 2012 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module top_n_outlier_pruning_block (
        dummy,
        ap_return
);

input  [7:0] dummy;
output  [31:0] ap_return;

parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_true = 1'b1;



assign ap_return = ap_const_lv32_0;


endmodule //top_n_outlier_pruning_block

