// ==============================================================
// File generated by AutoESL - High-Level Synthesis System (C, C++, SystemC)
// Version: 2012.1
// Copyright (C) 2012 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xbasic.h"

/************************** Function Implementation *************************/
int XBasic_Initialize(XBasic *InstancePtr, XBasic_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Bus_a_BaseAddress = ConfigPtr->Bus_a_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}

void XBasic_Start(XBasic *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBasic_WriteReg(InstancePtr->Bus_a_BaseAddress, XBASIC_BUS_A_ADDR_AP_CTRL, 1);
}

u32 XBasic_IsDone(XBasic *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBasic_ReadReg(InstancePtr->Bus_a_BaseAddress, XBASIC_BUS_A_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XBasic_IsIdle(XBasic *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBasic_ReadReg(InstancePtr->Bus_a_BaseAddress, XBASIC_BUS_A_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

void XBasic_SetA(XBasic *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBasic_WriteReg(InstancePtr->Bus_a_BaseAddress, XBASIC_BUS_A_ADDR_A_DATA, Data);
}

u32 XBasic_GetA(XBasic *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBasic_ReadReg(InstancePtr->Bus_a_BaseAddress, XBASIC_BUS_A_ADDR_A_DATA);
    return Data;
}

void XBasic_SetB(XBasic *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBasic_WriteReg(InstancePtr->Bus_a_BaseAddress, XBASIC_BUS_A_ADDR_B_DATA, Data);
}

u32 XBasic_GetB(XBasic *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBasic_ReadReg(InstancePtr->Bus_a_BaseAddress, XBASIC_BUS_A_ADDR_B_DATA);
    return Data;
}

u32 XBasic_GetC(XBasic *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBasic_ReadReg(InstancePtr->Bus_a_BaseAddress, XBASIC_BUS_A_ADDR_C_DATA);
    return Data;
}

void XBasic_InterruptGlobalEnable(XBasic *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBasic_WriteReg(InstancePtr->Bus_a_BaseAddress, XBASIC_BUS_A_ADDR_GIE, 1);
}

void XBasic_InterruptGlobalDisable(XBasic *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBasic_WriteReg(InstancePtr->Bus_a_BaseAddress, XBASIC_BUS_A_ADDR_GIE, 0);
}

void XBasic_InterruptEnable(XBasic *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XBasic_ReadReg(InstancePtr->Bus_a_BaseAddress, XBASIC_BUS_A_ADDR_IER);
    XBasic_WriteReg(InstancePtr->Bus_a_BaseAddress, XBASIC_BUS_A_ADDR_IER, Register | Mask);
}

void XBasic_InterruptDisable(XBasic *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XBasic_ReadReg(InstancePtr->Bus_a_BaseAddress, XBASIC_BUS_A_ADDR_IER);
    XBasic_WriteReg(InstancePtr->Bus_a_BaseAddress, XBASIC_BUS_A_ADDR_IER, Register & (~Mask));
}

void XBasic_InterruptClear(XBasic *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XBasic_ReadReg(InstancePtr->Bus_a_BaseAddress, XBASIC_BUS_A_ADDR_ISR);
    XBasic_WriteReg(InstancePtr->Bus_a_BaseAddress, XBASIC_BUS_A_ADDR_ISR, Register & Mask);
}

u32 XBasic_InterruptGetEnabled(XBasic *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XBasic_ReadReg(InstancePtr->Bus_a_BaseAddress, XBASIC_BUS_A_ADDR_IER);
}

u32 XBasic_InterruptGetStatus(XBasic *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XBasic_ReadReg(InstancePtr->Bus_a_BaseAddress, XBASIC_BUS_A_ADDR_ISR);
}

