// ==============================================================
// File generated by AutoESL - High-Level Synthesis System (C, C++, SystemC)
// Version: 2012.1
// Copyright (C) 2012 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xdistance_squared.h"

/************************** Function Implementation *************************/
int XDistance_squared_Initialize(XDistance_squared *InstancePtr, XDistance_squared_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_bus_BaseAddress = ConfigPtr->Control_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}

void XDistance_squared_Start(XDistance_squared *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDistance_squared_WriteReg(InstancePtr->Control_bus_BaseAddress, XDISTANCE_SQUARED_CONTROL_BUS_ADDR_AP_CTRL, 1);
}

u32 XDistance_squared_IsDone(XDistance_squared *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDistance_squared_ReadReg(InstancePtr->Control_bus_BaseAddress, XDISTANCE_SQUARED_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XDistance_squared_IsIdle(XDistance_squared *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDistance_squared_ReadReg(InstancePtr->Control_bus_BaseAddress, XDISTANCE_SQUARED_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u64 XDistance_squared_GetSum(XDistance_squared *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDistance_squared_ReadReg(InstancePtr->Control_bus_BaseAddress, XDISTANCE_SQUARED_CONTROL_BUS_ADDR_SUM_DATA);
    Data += (u64)XDistance_squared_ReadReg(InstancePtr->Control_bus_BaseAddress, XDISTANCE_SQUARED_CONTROL_BUS_ADDR_SUM_DATA) << 32;
    return Data;
}

void XDistance_squared_InterruptGlobalEnable(XDistance_squared *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDistance_squared_WriteReg(InstancePtr->Control_bus_BaseAddress, XDISTANCE_SQUARED_CONTROL_BUS_ADDR_GIE, 1);
}

void XDistance_squared_InterruptGlobalDisable(XDistance_squared *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDistance_squared_WriteReg(InstancePtr->Control_bus_BaseAddress, XDISTANCE_SQUARED_CONTROL_BUS_ADDR_GIE, 0);
}

void XDistance_squared_InterruptEnable(XDistance_squared *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XDistance_squared_ReadReg(InstancePtr->Control_bus_BaseAddress, XDISTANCE_SQUARED_CONTROL_BUS_ADDR_IER);
    XDistance_squared_WriteReg(InstancePtr->Control_bus_BaseAddress, XDISTANCE_SQUARED_CONTROL_BUS_ADDR_IER, Register | Mask);
}

void XDistance_squared_InterruptDisable(XDistance_squared *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XDistance_squared_ReadReg(InstancePtr->Control_bus_BaseAddress, XDISTANCE_SQUARED_CONTROL_BUS_ADDR_IER);
    XDistance_squared_WriteReg(InstancePtr->Control_bus_BaseAddress, XDISTANCE_SQUARED_CONTROL_BUS_ADDR_IER, Register & (~Mask));
}

void XDistance_squared_InterruptClear(XDistance_squared *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XDistance_squared_ReadReg(InstancePtr->Control_bus_BaseAddress, XDISTANCE_SQUARED_CONTROL_BUS_ADDR_ISR);
    XDistance_squared_WriteReg(InstancePtr->Control_bus_BaseAddress, XDISTANCE_SQUARED_CONTROL_BUS_ADDR_ISR, Register & Mask);
}

u32 XDistance_squared_InterruptGetEnabled(XDistance_squared *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDistance_squared_ReadReg(InstancePtr->Control_bus_BaseAddress, XDISTANCE_SQUARED_CONTROL_BUS_ADDR_IER);
}

u32 XDistance_squared_InterruptGetStatus(XDistance_squared *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDistance_squared_ReadReg(InstancePtr->Control_bus_BaseAddress, XDISTANCE_SQUARED_CONTROL_BUS_ADDR_ISR);
}

