// ==============================================================
// File generated by AutoESL - High-Level Synthesis System (C, C++, SystemC)
// Version: 2012.1
// Copyright (C) 2012 Xilinx Inc. All rights reserved.
// 
// ==============================================================

`timescale 1 ns / 1 ps
module basic_top (
s_axi_BUS_A_ACLK,
s_axi_BUS_A_ARESETN,
s_axi_BUS_A_AWADDR,
s_axi_BUS_A_AWVALID,
s_axi_BUS_A_AWREADY,
s_axi_BUS_A_WDATA,
s_axi_BUS_A_WSTRB,
s_axi_BUS_A_WVALID,
s_axi_BUS_A_WREADY,
s_axi_BUS_A_BRESP,
s_axi_BUS_A_BVALID,
s_axi_BUS_A_BREADY,
s_axi_BUS_A_ARADDR,
s_axi_BUS_A_ARVALID,
s_axi_BUS_A_ARREADY,
s_axi_BUS_A_RDATA,
s_axi_BUS_A_RRESP,
s_axi_BUS_A_RVALID,
s_axi_BUS_A_RREADY,
interrupt,
SYS_RESET,
SYS_CLK
);

parameter C_S_AXI_BUS_A_ADDR_WIDTH = 32;
parameter C_S_AXI_BUS_A_DATA_WIDTH = 32;
parameter RESET_ACTIVE_LOW = 1;
input s_axi_BUS_A_ACLK ;
input s_axi_BUS_A_ARESETN ;
input [C_S_AXI_BUS_A_ADDR_WIDTH - 1:0] s_axi_BUS_A_AWADDR ;
input s_axi_BUS_A_AWVALID ;
output s_axi_BUS_A_AWREADY ;
input [C_S_AXI_BUS_A_DATA_WIDTH - 1:0] s_axi_BUS_A_WDATA ;
input [C_S_AXI_BUS_A_DATA_WIDTH/8 - 1:0] s_axi_BUS_A_WSTRB ;
input s_axi_BUS_A_WVALID ;
output s_axi_BUS_A_WREADY ;
output [2 - 1:0] s_axi_BUS_A_BRESP ;
output s_axi_BUS_A_BVALID ;
input s_axi_BUS_A_BREADY ;
input [C_S_AXI_BUS_A_ADDR_WIDTH - 1:0] s_axi_BUS_A_ARADDR ;
input s_axi_BUS_A_ARVALID ;
output s_axi_BUS_A_ARREADY ;
output [C_S_AXI_BUS_A_DATA_WIDTH - 1:0] s_axi_BUS_A_RDATA ;
output [2 - 1:0] s_axi_BUS_A_RRESP ;
output s_axi_BUS_A_RVALID ;
input s_axi_BUS_A_RREADY ;
output interrupt ;

input SYS_RESET ;

input SYS_CLK ;

wire s_axi_BUS_A_ACLK;
wire s_axi_BUS_A_ARESETN;
wire [C_S_AXI_BUS_A_ADDR_WIDTH - 1:0] s_axi_BUS_A_AWADDR;
wire s_axi_BUS_A_AWVALID;
wire s_axi_BUS_A_AWREADY;
wire [C_S_AXI_BUS_A_DATA_WIDTH - 1:0] s_axi_BUS_A_WDATA;
wire [C_S_AXI_BUS_A_DATA_WIDTH/8 - 1:0] s_axi_BUS_A_WSTRB;
wire s_axi_BUS_A_WVALID;
wire s_axi_BUS_A_WREADY;
wire [2 - 1:0] s_axi_BUS_A_BRESP;
wire s_axi_BUS_A_BVALID;
wire s_axi_BUS_A_BREADY;
wire [C_S_AXI_BUS_A_ADDR_WIDTH - 1:0] s_axi_BUS_A_ARADDR;
wire s_axi_BUS_A_ARVALID;
wire s_axi_BUS_A_ARREADY;
wire [C_S_AXI_BUS_A_DATA_WIDTH - 1:0] s_axi_BUS_A_RDATA;
wire [2 - 1:0] s_axi_BUS_A_RRESP;
wire s_axi_BUS_A_RVALID;
wire s_axi_BUS_A_RREADY;
wire interrupt;

wire SYS_RESET;


wire [8 - 1:0] sig_basic_a;
wire [8 - 1:0] sig_basic_b;
wire [8 - 1:0] sig_basic_c;
wire sig_basic_ap_start;
wire sig_basic_ap_done;
wire sig_basic_ap_idle;

wire sig_basic_ap_rst;




basic basic_U(
    .a(sig_basic_a),
    .b(sig_basic_b),
    .c(sig_basic_c),
    .ap_start(sig_basic_ap_start),
    .ap_done(sig_basic_ap_done),
    .ap_idle(sig_basic_ap_idle),
    .ap_rst(sig_basic_ap_rst),
    .ap_clk(SYS_CLK)
);

BUS_A_if #(
    .C_ADDR_WIDTH(C_S_AXI_BUS_A_ADDR_WIDTH),
    .C_DATA_WIDTH(C_S_AXI_BUS_A_DATA_WIDTH))
BUS_A_if_U(
    .I_a(sig_basic_a),
    .I_b(sig_basic_b),
    .O_c(sig_basic_c),
    .I_ap_start(sig_basic_ap_start),
    .O_ap_done(sig_basic_ap_done),
    .O_ap_idle(sig_basic_ap_idle),
    .ACLK(s_axi_BUS_A_ACLK),
    .ARESETN(s_axi_BUS_A_ARESETN),
    .AWADDR(s_axi_BUS_A_AWADDR),
    .AWVALID(s_axi_BUS_A_AWVALID),
    .AWREADY(s_axi_BUS_A_AWREADY),
    .WDATA(s_axi_BUS_A_WDATA),
    .WSTRB(s_axi_BUS_A_WSTRB),
    .WVALID(s_axi_BUS_A_WVALID),
    .WREADY(s_axi_BUS_A_WREADY),
    .BRESP(s_axi_BUS_A_BRESP),
    .BVALID(s_axi_BUS_A_BVALID),
    .BREADY(s_axi_BUS_A_BREADY),
    .ARADDR(s_axi_BUS_A_ARADDR),
    .ARVALID(s_axi_BUS_A_ARVALID),
    .ARREADY(s_axi_BUS_A_ARREADY),
    .RDATA(s_axi_BUS_A_RDATA),
    .RRESP(s_axi_BUS_A_RRESP),
    .RVALID(s_axi_BUS_A_RVALID),
    .RREADY(s_axi_BUS_A_RREADY),
    .interrupt(interrupt));

basic_ap_rst_if #(
    .RESET_ACTIVE_LOW(RESET_ACTIVE_LOW))
ap_rst_if_U(
    .dout(sig_basic_ap_rst),
    .din(SYS_RESET));

endmodule
