#################################################################
# Makefile generated by Xilinx Platform Studio 
# Project:D:\Josh\ThesisCode\TopN_Outlier_Pruning_Block\FPGA\PlanAhead\NO_BLOCKING\NO_BLOCKING.srcs\sources_1\edk\system\system.xmp
#
# WARNING : This file will be re-generated every time a command
# to run a make target is invoked. So, any changes made to this  
# file manually, will be lost when make is invoked next. 
#################################################################

SHELL = CMD

XILINX_EDK_DIR = C:/Xilinx/14.2/ISE_DS/EDK

SYSTEM = system

MHSFILE = system.mhs

PCWPRJFILE = data/ps7_system_prj.xml

FPGA_ARCH = zynq

DEVICE = xc7z020clg484-1

INTSTYLE = pa

XPS_HDL_LANG = verilog
GLOBAL_SEARCHPATHOPT = 
PROJECT_SEARCHPATHOPT = 

SEARCHPATHOPT = $(PROJECT_SEARCHPATHOPT) $(GLOBAL_SEARCHPATHOPT)

SUBMODULE_OPT =  -toplevel no -ti system_i

PLATGEN_OPTIONS = -p $(DEVICE) -lang $(XPS_HDL_LANG) -intstyle $(INTSTYLE) $(SEARCHPATHOPT) $(SUBMODULE_OPT) -msg __xps/ise/xmsgprops.lst

OBSERVE_PAR_OPTIONS = -error yes

MICROBLAZE_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop.elf
MICROBLAZE_BOOTLOOP_LE = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop_le.elf
PPC405_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc405/ppc_bootloop.elf
PPC440_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc440/ppc440_bootloop.elf
BOOTLOOP_DIR = bootloops

BRAMINIT_ELF_IMP_FILES =
BRAMINIT_ELF_IMP_FILE_ARGS =

BRAMINIT_ELF_SIM_FILES =
BRAMINIT_ELF_SIM_FILE_ARGS =

SIM_CMD = isim_system

BEHAVIORAL_SIM_SCRIPT = simulation/behavioral/$(SYSTEM)_setup.tcl

STRUCTURAL_SIM_SCRIPT = simulation/structural/$(SYSTEM)_setup.tcl

TIMING_SIM_SCRIPT = simulation/timing/$(SYSTEM)_setup.tcl

DEFAULT_SIM_SCRIPT = $(BEHAVIORAL_SIM_SCRIPT)

SIMGEN_OPTIONS = -p $(DEVICE) -lang $(XPS_HDL_LANG) -intstyle $(INTSTYLE) $(SEARCHPATHOPT) $(BRAMINIT_ELF_SIM_FILE_ARGS) -msg __xps/ise/xmsgprops.lst -s isim -X D:/Josh/ThesisCode/TopN_Outlier_Pruning_Block/FPGA/PlanAhead/NO_BLOCKING/NO_BLOCKING.srcs/sources_1/edk/system/


CORE_STATE_DEVELOPMENT_FILES = pcores/distance_squared_top_v1_00_a/netlist/distance_squared_ap_dadddsub_3_full_dsp.ngc \
pcores/distance_squared_top_v1_00_a/netlist/distance_squared_ap_dadd_3_full_dsp.ngc \
pcores/distance_squared_top_v1_00_a/netlist/distance_squared_ap_dcmp_1_no_dsp.ngc \
pcores/distance_squared_top_v1_00_a/netlist/distance_squared_ap_dmul_3_max_dsp.ngc \
pcores/distance_squared_top_v1_00_a/netlist/distance_squared_ap_sitodp_3_no_dsp.ngc \
pcores/distance_squared_top_v1_00_a/netlist/distance_squared_sum_of_squares_split_ram.ngc \
pcores/distance_squared_top_v1_00_a/synhdl/verilog/CONTROL_BUS_if.v \
pcores/distance_squared_top_v1_00_a/synhdl/verilog/INPUT_STREAM_A_if.v \
pcores/distance_squared_top_v1_00_a/synhdl/verilog/INPUT_STREAM_B_if.v \
pcores/distance_squared_top_v1_00_a/synhdl/verilog/distance_squared_ap_dadddsub_3_full_dsp.v \
pcores/distance_squared_top_v1_00_a/synhdl/verilog/distance_squared_grp_fu_215_ACMP_dadddsub_1.v \
pcores/distance_squared_top_v1_00_a/synhdl/verilog/distance_squared_ap_dadd_3_full_dsp.v \
pcores/distance_squared_top_v1_00_a/synhdl/verilog/distance_squared_grp_fu_219_ACMP_dadd_2.v \
pcores/distance_squared_top_v1_00_a/synhdl/verilog/distance_squared_ap_dmul_3_max_dsp.v \
pcores/distance_squared_top_v1_00_a/synhdl/verilog/distance_squared_grp_fu_224_ACMP_dmul_3.v \
pcores/distance_squared_top_v1_00_a/synhdl/verilog/distance_squared_ap_dcmp_1_no_dsp.v \
pcores/distance_squared_top_v1_00_a/synhdl/verilog/distance_squared_grp_fu_228_ACMP_dcmp_4.v \
pcores/distance_squared_top_v1_00_a/synhdl/verilog/distance_squared_ap_sitodp_3_no_dsp.v \
pcores/distance_squared_top_v1_00_a/synhdl/verilog/distance_squared_grp_fu_234_ACMP_sitodp_5.v \
pcores/distance_squared_top_v1_00_a/synhdl/verilog/distance_squared_grp_fu_237_ACMP_sitodp_6.v \
pcores/distance_squared_top_v1_00_a/synhdl/verilog/distance_squared_sum_of_squares_split_ram.v \
pcores/distance_squared_top_v1_00_a/synhdl/verilog/distance_squared_sum_of_squares_split.v \
pcores/distance_squared_top_v1_00_a/synhdl/verilog/distance_squared.v \
pcores/distance_squared_top_v1_00_a/synhdl/verilog/distance_squared_ap_rst_if.v \
pcores/distance_squared_top_v1_00_a/synhdl/verilog/distance_squared_top.v

WRAPPER_NGC_FILES = implementation/system_processing_system7_0_wrapper.ngc \
implementation/system_axi_interconnect_1_wrapper.ngc \
implementation/system_distance_squared_top_0_wrapper.ngc

POSTSYN_NETLIST = implementation/$(SYSTEM).ngc

SYSTEM_BIT = implementation/$(SYSTEM).bit

DOWNLOAD_BIT = implementation/download.bit

SYSTEM_ACE = implementation/$(SYSTEM).ace

UCF_FILE = data\system.ucf

BMM_FILE = implementation/$(SYSTEM).bmm

BITGEN_UT_FILE = etc/bitgen.ut

XFLOW_OPT_FILE = etc/fast_runtime.opt
XFLOW_DEPENDENCY = __xps/xpsxflow.opt $(XFLOW_OPT_FILE)

XPLORER_DEPENDENCY = __xps/xplorer.opt
XPLORER_OPTIONS = -p $(DEVICE) -uc $(SYSTEM).ucf -bm $(SYSTEM).bmm -max_runs 7

FPGA_IMP_DEPENDENCY = $(BMM_FILE) $(POSTSYN_NETLIST) $(UCF_FILE) $(XFLOW_DEPENDENCY)

SDK_EXPORT_DIR = SDK\SDK_Export\hw
SYSTEM_HW_HANDOFF = $(SDK_EXPORT_DIR)/$(SYSTEM).xml
SYSTEM_HW_HANDOFF_BIT = $(SDK_EXPORT_DIR)/$(SYSTEM).bit
SYSTEM_HW_HANDOFF_DEP = $(SYSTEM_HW_HANDOFF) $(SYSTEM_HW_HANDOFF_BIT)
