######################################################
#
# XPS Tcl API script generated by PlanAhead
#
######################################################

proc _main_ {} {
  cd "D:/Josh/ThesisCode/TopN_Outlier_Pruning_Block/FPGA/PlanAhead/NO_BLOCKING/NO_BLOCKING.srcs/sources_1/edk/system"
  if { [ catch {xload xmp system.xmp} result ] } {
    exit 10
  }
  run drc
  return $result
}

# Run DRC
if { [catch {_main_} result] } {
  exit -1
}

# Check return status and exit
if { [string length $result] == 0 } {
  exit 0
} else {
  exit $result
}
