-- ==============================================================
-- File generated by AutoESL - High-Level Synthesis System (C, C++, SystemC)
-- Version: 2012.1
-- Copyright (C) 2012 Xilinx Inc. All rights reserved.
-- 
-- ==============================================================

Library IEEE;
use IEEE.std_logic_1164.all;
Library work;
use work.all;
use work.AESL_components.all;

entity distance_squared_sum_of_squares_split is
    generic (
        DataWidth : INTEGER := 64;
        AddressRange : INTEGER := 8;
        AddressWidth : INTEGER := 3);
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0);
        q0 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0);
        address1 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0));
end entity;

architecture arch of distance_squared_sum_of_squares_split is
    component distance_squared_sum_of_squares_split_ram is
        port (
            clka : IN STD_LOGIC;
            dina : IN STD_LOGIC_VECTOR;
            addra : IN STD_LOGIC_VECTOR;
            wea : IN STD_LOGIC_VECTOR;
            douta : OUT STD_LOGIC_VECTOR;
            ena : IN STD_LOGIC;
            clkb : IN STD_LOGIC;
            dinb : IN STD_LOGIC_VECTOR;
            addrb : IN STD_LOGIC_VECTOR;
            web : IN STD_LOGIC_VECTOR;
            doutb : OUT STD_LOGIC_VECTOR;
            enb : IN STD_LOGIC);
    end component;

    signal sig_we0 : STD_LOGIC_VECTOR(1 - 1 DOWNTO 0);
    signal sig_ena : STD_LOGIC;
    signal sig_d0 : STD_LOGIC_VECTOR(64 - 1 DOWNTO 0);
    signal sig_q0 : STD_LOGIC_VECTOR(64 - 1 DOWNTO 0);
    signal sig_we1 : STD_LOGIC_VECTOR(1 - 1 DOWNTO 0);
    signal sig_enb : STD_LOGIC;
    signal sig_d1 : STD_LOGIC_VECTOR(64 - 1 DOWNTO 0);
    signal sig_q1 : STD_LOGIC_VECTOR(64 - 1 DOWNTO 0);


begin
    distance_squared_sum_of_squares_split_ram_U :  component distance_squared_sum_of_squares_split_ram
    port map (
        clka => clk,
        dina => sig_d0,
        addra => address0,
        wea => sig_we0,
        douta => sig_q0,
        ena => sig_ena,
        clkb => clk,
        dinb => sig_d1,
        addrb => address1,
        web => sig_we1,
        doutb => sig_q1,
        enb => sig_enb);

sig_we0(0) <= we0;
sig_d0 <= d0;
q0 <= sig_q0;
sig_ena <= ce0;
sig_we1(0) <= we1;
sig_d1 <= d1;
sig_enb <= ce1;
end architecture;

