# ==============================================================
# File generated by AutoESL - High-Level Synthesis System (C, C++, SystemC)
# Version: 2012.1
# Copyright (C) 2012 Xilinx Inc. All rights reserved.
# 
# ==============================================================

#
# Settings for Xilinx implementation flow
#
set top_module distance_squared
set language vhdl
set family zynq
set device xc7z020
set package clg484
set speed -1
set clock ap_clk

# For customizing the implementation flow
set optimization_goal speed    ;# speed|area
set optimization_effort high   ;# normal|high
set register_duplication false ;# true|false
set register_balancing no      ;# yes|no
set par_effort high            ;# std|high|extra
set add_io_buffers false       ;# true/false
