// ==============================================================
// RTL generated by AutoESL - High-Level Synthesis System (C, C++, SystemC)
// Version: 2012.1
// Copyright (C) 2012 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _top_n_outlier_pruning_block_HH_
#define _top_n_outlier_pruning_block_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct top_n_outlier_pruning_block : public sc_module {
    // Port declarations 2
    sc_in< sc_lv<8> > dummy;
    sc_out< sc_lv<32> > ap_return;
    // Port declarations for the virtual clock. 
    sc_in_clk ap_virtual_clock;


    // Module declarations
    top_n_outlier_pruning_block(sc_module_name name);
    SC_HAS_PROCESS(top_n_outlier_pruning_block);

    ~top_n_outlier_pruning_block();

    sc_trace_file* mVcdFile;

    static const sc_lv<32> ap_const_lv32_0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_return();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
