#pragma line 1 "distance_squared.c" ::: -10
#pragma line 1 "<built-in>" ::: -9
#pragma line 1 "<command-line>" ::: -8
#pragma line 1 "C:/Xilinx/2012.1/AutoESL/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: -7
#pragma line 222 "C:/Xilinx/2012.1/AutoESL/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 0
#pragma line 1 "<command-line>" 2 ::: 3
#pragma line 1 "distance_squared.c" ::: 4
#pragma line 1 "distance_squared.h" 1 ::: 5
#pragma line 1 "c:/xilinx/2012.1/autoesl/win_x86/tools/llvm_gcc/bin/../lib/gcc/i686-pc-mingw32/4.2.1/../../../../include/stdlib.h" 1 3 ::: 9
#pragma line 1 "c:/xilinx/2012.1/autoesl/win_x86/tools/llvm_gcc/bin/../lib/gcc/i686-pc-mingw32/4.2.1/../../../../include/_mingw.h" 1 3 ::: 24
#pragma line 31 "c:/xilinx/2012.1/autoesl/win_x86/tools/llvm_gcc/bin/../lib/gcc/i686-pc-mingw32/4.2.1/../../../../include/_mingw.h" 3 ::: 47
#pragma line 32 "c:/xilinx/2012.1/autoesl/win_x86/tools/llvm_gcc/bin/../lib/gcc/i686-pc-mingw32/4.2.1/../../../../include/_mingw.h" 3 ::: 49
#pragma line 121 "c:/xilinx/2012.1/autoesl/win_x86/tools/llvm_gcc/bin/../lib/gcc/i686-pc-mingw32/4.2.1/../../../../include/_mingw.h" 3 ::: 95
#pragma line 140 "c:/xilinx/2012.1/autoesl/win_x86/tools/llvm_gcc/bin/../lib/gcc/i686-pc-mingw32/4.2.1/../../../../include/_mingw.h" 3 ::: 98
#pragma line 230 "c:/xilinx/2012.1/autoesl/win_x86/tools/llvm_gcc/bin/../lib/gcc/i686-pc-mingw32/4.2.1/../../../../include/_mingw.h" 3 ::: 104
#pragma line 252 "c:/xilinx/2012.1/autoesl/win_x86/tools/llvm_gcc/bin/../lib/gcc/i686-pc-mingw32/4.2.1/../../../../include/_mingw.h" 3 ::: 108
#pragma line 277 "c:/xilinx/2012.1/autoesl/win_x86/tools/llvm_gcc/bin/../lib/gcc/i686-pc-mingw32/4.2.1/../../../../include/_mingw.h" 3 ::: 123
#pragma line 16 "c:/xilinx/2012.1/autoesl/win_x86/tools/llvm_gcc/bin/../lib/gcc/i686-pc-mingw32/4.2.1/../../../../include/stdlib.h" 2 3 ::: 127
#pragma line 1 "c:/xilinx/2012.1/autoesl/win_x86/tools/llvm_gcc/bin/../lib/gcc/i686-pc-mingw32/4.2.1/include/stddef.h" 1 3 4 ::: 133
#pragma line 52 "c:/xilinx/2012.1/autoesl/win_x86/tools/llvm_gcc/bin/../lib/gcc/i686-pc-mingw32/4.2.1/include/stddef.h" 3 4 ::: 173
#pragma line 97 "c:/xilinx/2012.1/autoesl/win_x86/tools/llvm_gcc/bin/../lib/gcc/i686-pc-mingw32/4.2.1/include/stddef.h" 3 4 ::: 190
#pragma line 122 "c:/xilinx/2012.1/autoesl/win_x86/tools/llvm_gcc/bin/../lib/gcc/i686-pc-mingw32/4.2.1/include/stddef.h" 3 4 ::: 203
#pragma line 167 "c:/xilinx/2012.1/autoesl/win_x86/tools/llvm_gcc/bin/../lib/gcc/i686-pc-mingw32/4.2.1/include/stddef.h" 3 4 ::: 214
#pragma line 214 "c:/xilinx/2012.1/autoesl/win_x86/tools/llvm_gcc/bin/../lib/gcc/i686-pc-mingw32/4.2.1/include/stddef.h" 3 4 ::: 219
#pragma line 240 "c:/xilinx/2012.1/autoesl/win_x86/tools/llvm_gcc/bin/../lib/gcc/i686-pc-mingw32/4.2.1/include/stddef.h" 3 4 ::: 221
#pragma line 281 "c:/xilinx/2012.1/autoesl/win_x86/tools/llvm_gcc/bin/../lib/gcc/i686-pc-mingw32/4.2.1/include/stddef.h" 3 4 ::: 229
#pragma line 308 "c:/xilinx/2012.1/autoesl/win_x86/tools/llvm_gcc/bin/../lib/gcc/i686-pc-mingw32/4.2.1/include/stddef.h" 3 4 ::: 240
#pragma line 326 "c:/xilinx/2012.1/autoesl/win_x86/tools/llvm_gcc/bin/../lib/gcc/i686-pc-mingw32/4.2.1/include/stddef.h" 3 4 ::: 244
#pragma line 360 "c:/xilinx/2012.1/autoesl/win_x86/tools/llvm_gcc/bin/../lib/gcc/i686-pc-mingw32/4.2.1/include/stddef.h" 3 4 ::: 246
#pragma line 395 "c:/xilinx/2012.1/autoesl/win_x86/tools/llvm_gcc/bin/../lib/gcc/i686-pc-mingw32/4.2.1/include/stddef.h" 3 4 ::: 250
#pragma line 22 "c:/xilinx/2012.1/autoesl/win_x86/tools/llvm_gcc/bin/../lib/gcc/i686-pc-mingw32/4.2.1/../../../../include/stdlib.h" 2 3 ::: 252
#pragma line 65 "c:/xilinx/2012.1/autoesl/win_x86/tools/llvm_gcc/bin/../lib/gcc/i686-pc-mingw32/4.2.1/../../../../include/stdlib.h" 3 ::: 273
#pragma line 105 "c:/xilinx/2012.1/autoesl/win_x86/tools/llvm_gcc/bin/../lib/gcc/i686-pc-mingw32/4.2.1/../../../../include/stdlib.h" 3 ::: 289
#pragma line 129 "c:/xilinx/2012.1/autoesl/win_x86/tools/llvm_gcc/bin/../lib/gcc/i686-pc-mingw32/4.2.1/../../../../include/stdlib.h" 3 ::: 298
#pragma line 166 "c:/xilinx/2012.1/autoesl/win_x86/tools/llvm_gcc/bin/../lib/gcc/i686-pc-mingw32/4.2.1/../../../../include/stdlib.h" 3 ::: 321
#pragma line 196 "c:/xilinx/2012.1/autoesl/win_x86/tools/llvm_gcc/bin/../lib/gcc/i686-pc-mingw32/4.2.1/../../../../include/stdlib.h" 3 ::: 329
#pragma line 258 "c:/xilinx/2012.1/autoesl/win_x86/tools/llvm_gcc/bin/../lib/gcc/i686-pc-mingw32/4.2.1/../../../../include/stdlib.h" 3 ::: 358
#pragma line 275 "c:/xilinx/2012.1/autoesl/win_x86/tools/llvm_gcc/bin/../lib/gcc/i686-pc-mingw32/4.2.1/../../../../include/stdlib.h" 3 ::: 364
#pragma line 293 "c:/xilinx/2012.1/autoesl/win_x86/tools/llvm_gcc/bin/../lib/gcc/i686-pc-mingw32/4.2.1/../../../../include/stdlib.h" 3 ::: 369
#pragma line 303 "c:/xilinx/2012.1/autoesl/win_x86/tools/llvm_gcc/bin/../lib/gcc/i686-pc-mingw32/4.2.1/../../../../include/stdlib.h" 3 ::: 371
#pragma line 485 "c:/xilinx/2012.1/autoesl/win_x86/tools/llvm_gcc/bin/../lib/gcc/i686-pc-mingw32/4.2.1/../../../../include/stdlib.h" 3 ::: 518
#pragma line 5 "distance_squared.h" 2 ::: 569
#pragma line 2 "distance_squared.c" 2 ::: 579
