%==========================================================================
% This script is used to generate a list of all profiles.
%==========================================================================

function profiles = all_profiles
    profiles = [
        struct('name', 'matlab_original',           'func', 'TopN_Outlier_Pruning_Block_MATLAB_ORIGINAL'), ...
        struct('name', 'matlab_original_inline',    'func', 'TopN_Outlier_Pruning_Block_MATLAB_ORIGINAL_INLINE'), ...
        struct('name', 'matlab_sorted',             'func', 'TopN_Outlier_Pruning_Block_MATLAB_SORTED'), ...
        struct('name', 'matlab_sorted_inline',      'func', 'TopN_Outlier_Pruning_Block_MATLAB_SORTED_INLINE'), ...
        struct('name', 'C_sorted',                  'func', 'TopN_Outlier_Pruning_Block_C_SORTED'), ...
        struct('name', 'C_unsorted',                'func', 'TopN_Outlier_Pruning_Block_C_UNSORTED'), ...
        struct('name', 'C_no_blocking',             'func', 'TopN_Outlier_Pruning_Block_C_NO_BLOCKING'), ...
    ];
